import hoodie from '../../Assets/men/Allen Solly/Hoodie/1.jpeg'
import jeans from '../../Assets/men/Allen Solly/Jeans/25.jpeg'
import shirt from '../../Assets/men/Allen Solly/Shirt/1.jpeg'
import pant from '../../Assets/men/Allen Solly/Pant/1.jpeg'
import lower from '../../Assets/men/Allen Solly/Lower/1.jpeg'
import t_shirt from '../../Assets/men/Allen Solly/T-shirt/1.jpeg'

let allen_solly=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Hoodie",
        image:hoodie,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Jeans",
        image:jeans,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Shirt",
        image:shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Pant",
        image:pant,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Lower",
        image:lower,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"T-shirt",
        image:t_shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    }
]
export default allen_solly;

let mufti=[
    {
        id:1,
        brand:"Mufti",
        name:"Hoodie",
        image:hoodie,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:2,
        brand:"Mufti",
        name:"Jeans",
        image:jeans,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:3,
        brand:"Mufti",
        name:"Shirt",
        image:shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:4,
        brand:"Mufti",
        name:"Pant",
        image:pant,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:5,
        brand:"Mufti",
        name:"Lower",
        image:lower,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:6,
        brand:"Mufti",
        name:"T-shirt",
        image:t_shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    }
]
export {mufti}

let Cobb=[
    {
        id:1,
        brand:"Cobb Italy",
        name:"Hoodie",
        image:hoodie,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:2,
        brand:"Cobb Italy",
        name:"Jeans",
        image:jeans,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:3,
        brand:"Cobb Italy",
        name:"Shirt",
        image:shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:4,
        brand:"Cobb Italy",
        name:"Pant",
        image:pant,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:5,
        brand:"Cobb Italy",
        name:"Lower",
        image:lower,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:6,
        brand:"Cobb Italy",
        name:"T-shirt",
        image:t_shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    }
]
export {Cobb}

let adidas=[
    {
        id:1,
        brand:"Adidas",
        name:"Hoodie",
        image:hoodie,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:2,
        brand:"Adidas",
        name:"Jeans",
        image:jeans,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:3,
        brand:"Adidas",
        name:"Shirt",
        image:shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:4,
        brand:"Adidas",
        name:"Pant",
        image:pant,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:5,
        brand:"Adidas",
        name:"Lower",
        image:lower,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:6,
        brand:"Adidas",
        name:"T-shirt",
        image:t_shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    }
]
export {adidas}

let peter_england=[
    {
        id:1,
        brand:"Peter England",
        name:"Hoodie",
        image:hoodie,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:2,
        brand:"Peter England",
        name:"Jeans",
        image:jeans,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:3,
        brand:"Peter England",
        name:"Shirt",
        image:shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:4,
        brand:"Peter England",
        name:"Pant",
        image:pant,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:5,
        brand:"Peter England",
        name:"Lower",
        image:lower,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:6,
        brand:"Peter England",
        name:"T-shirt",
        image:t_shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    }
]
export {peter_england}

let nike=[
    {
        id:1,
        brand:"Nike",
        name:"Hoodie",
        image:hoodie,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:2,
        brand:"Nike",
        name:"Jeans",
        image:jeans,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:3,
        brand:"Peter England",
        name:"Shirt",
        image:shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:4,
        brand:"Nike",
        name:"Pant",
        image:pant,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:5,
        brand:"Nike",
        name:"Lower",
        image:lower,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:6,
        brand:"Nike",
        name:"T-shirt",
        image:t_shirt,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    }
]
export {nike}