

let coatPant_product=[
    {
        id:1,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp1,
        new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp2,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp3,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp4,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp5,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp6,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp7,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp8,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp9,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp10,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp11,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp12,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp13,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp14,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    // {
    //     id:15,
    //     brand:"Coat Pant",
    //     name:"Men Slim Fit Single Breasted 2 Piece",
    //     image:cp15,
    //     new_price:"₹1379",
    //     old_price:"₹2299",
    //     offer:"40% off",
    //     rating:"4.3★",
    //     review:1256,
    //     size:"M , L , XL",
    // },
    {
        id:16,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp16,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp17,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp18,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp19,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp20,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp21,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp22,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp23,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp24,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp25,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp26,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp27,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp28,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp29,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp30,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp31,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp32,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp33,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp34,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:35,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp35,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:36,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp36,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:37,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp37,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:38,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp38,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:39,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp39,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:40,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp40,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:41,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp41,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:42,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp42,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:43,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp43,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:44,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp44,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:45,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp45,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:46,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp46,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:47,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp47,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:48,
        brand:"Coat Pant",
        name:"Men Slim Fit Single Breasted 2 Piece",
        image:cp48,
       new_price:"₹5599",
        old_price:"₹7099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]

export default coatPant_product