
let hoodie_product=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:13,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
    {
        id:14,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
    },
]

export default hoodie_product