import h1 from '../../Assets/men/Allen Solly/Hoodie/1.jpeg'
import h2 from '../../Assets/men/Allen Solly/Hoodie/2.jpeg'
import h3 from '../../Assets/men/Allen Solly/Hoodie/3.jpeg'
import h4 from '../../Assets/men/Allen Solly/Hoodie/4.jpeg'
import h5 from '../../Assets/men/Allen Solly/Hoodie/5.jpeg'
import h6 from '../../Assets/men/Allen Solly/Hoodie/6.jpeg'
import h7 from '../../Assets/men/Allen Solly/Hoodie/7.jpeg'
import h8 from '../../Assets/men/Allen Solly/Hoodie/8.jpeg'
import h9 from '../../Assets/men/Allen Solly/Hoodie/9.jpeg'
import h10 from '../../Assets/men/Allen Solly/Hoodie/10.jpeg'
import h11 from '../../Assets/men/Allen Solly/Hoodie/11.jpeg'
import h12 from '../../Assets/men/Allen Solly/Hoodie/12.jpeg'
import h13 from '../../Assets/men/Peter England/Hoodie/1.jpeg'
import h14 from '../../Assets/men/Peter England/Hoodie/2.jpeg'
import h15 from '../../Assets/men/Peter England/Hoodie/3.jpeg'
import h16 from '../../Assets/men/Peter England/Hoodie/4.jpeg'
import h17 from '../../Assets/men/Peter England/Hoodie/5.jpeg'
import h18 from '../../Assets/men/Peter England/Hoodie/6.jpeg'
import h19 from '../../Assets/men/Peter England/Hoodie/7.jpeg'
import h20 from '../../Assets/men/Peter England/Hoodie/8.jpeg'
import h21 from '../../Assets/men/Peter England/Hoodie/9.jpeg'
import h22 from '../../Assets/men/Peter England/Hoodie/10.jpeg'
import h23 from '../../Assets/men/Cobb/Hoodie/1.jpeg'
import h24 from '../../Assets/men/Cobb/Hoodie/2.jpeg'
import h25 from '../../Assets/men/Cobb/Hoodie/3.jpeg'
import h26 from '../../Assets/men/Cobb/Hoodie/4.jpeg'
import h27 from '../../Assets/men/Cobb/Hoodie/5.jpeg'
import h28 from '../../Assets/men/Cobb/Hoodie/6.jpeg'
import h29 from '../../Assets/men/Cobb/Hoodie/7.jpeg'
import h30 from '../../Assets/men/Cobb/Hoodie/8.jpeg'
import h31 from '../../Assets/men/Cobb/Hoodie/9.jpeg'
import h32 from '../../Assets/men/Cobb/Hoodie/10.jpeg'
import h33 from '../../Assets/men/Cobb/Hoodie/11.jpeg'
import h34 from '../../Assets/men/Cobb/Hoodie/12.jpeg'
import h35 from '../../Assets/men/Cobb/Hoodie/13.jpeg'
import h36 from '../../Assets/men/Nike/Hoodie/1.jpg'
import h37 from '../../Assets/men/Nike/Hoodie/2.jpeg'
import h38 from '../../Assets/men/Nike/Hoodie/3.jpeg'
import h39 from '../../Assets/men/Nike/Hoodie/4.jpeg'
import h40 from '../../Assets/men/Nike/Hoodie/5.jpeg'
import h41 from '../../Assets/men/Nike/Hoodie/6.jpeg'
import h42 from '../../Assets/men/Nike/Hoodie/7.jpeg'
import h43 from '../../Assets/men/Nike/Hoodie/8.jpeg'

let hoodie_product=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h2,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h3,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h4,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h5,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h6,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h7,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h8,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h9,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h10,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h11,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h12,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h13,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h15,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h16,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h17,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h18,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h19,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h20,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h21,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h22,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h24,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h25,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h26,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h27,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h28,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h29,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h30,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h31,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h32,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h33,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h34,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:35,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h35,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:36,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h36,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:37,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h37,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:38,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h38,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:39,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h39,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:40,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h40,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:41,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h41,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:42,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h42,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:43,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h43,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]

export default hoodie_product