import j1 from '../../Assets/men/Allen Solly/Jeans/1.jpeg'
import j2 from '../../Assets/men/Allen Solly/Jeans/2.jpeg'
import j3 from '../../Assets/men/Allen Solly/Jeans/3.jpeg'
import j4 from '../../Assets/men/Allen Solly/Jeans/4.jpeg'
import j5 from '../../Assets/men/Allen Solly/Jeans/5.jpeg'
import j6 from '../../Assets/men/Allen Solly/Jeans/6.jpeg'
import j7 from '../../Assets/men/Allen Solly/Jeans/7.jpeg'
import j8 from '../../Assets/men/Allen Solly/Jeans/8.jpeg'
import j9 from '../../Assets/men/Allen Solly/Jeans/9.jpeg'
import j10 from '../../Assets/men/Allen Solly/Jeans/10.jpeg'
import j11 from '../../Assets/men/Allen Solly/Jeans/11.jpeg'
import j12 from '../../Assets/men/Allen Solly/Jeans/12.jpeg'
import j13 from '../../Assets/men/Peter England/Jeans/1.jpeg'
import j14 from '../../Assets/men/Peter England/Jeans/2.jpeg'
import j15 from '../../Assets/men/Peter England/Jeans/3.jpeg'
import j16 from '../../Assets/men/Peter England/Jeans/4.jpeg'
import j17 from '../../Assets/men/Peter England/Jeans/5.jpeg'
import j18 from '../../Assets/men/Peter England/Jeans/6.jpeg'
import j19 from '../../Assets/men/Peter England/Jeans/7.jpeg'
import j20 from '../../Assets/men/Peter England/Jeans/8.jpeg'
import j21 from '../../Assets/men/Peter England/Jeans/9.jpeg'
import j22 from '../../Assets/men/Peter England/Jeans/10.jpeg'
import j23 from '../../Assets/men/Cobb/Jeans/1.jpeg'
import j24 from '../../Assets/men/Cobb/Jeans/2.jpeg'
import j25 from '../../Assets/men/Cobb/Jeans/3.jpeg'
import j26 from '../../Assets/men/Cobb/Jeans/4.jpeg'
import j27 from '../../Assets/men/Cobb/Jeans/5.jpeg'
import j28 from '../../Assets/men/Cobb/Jeans/6.jpeg'
import j29 from '../../Assets/men/Cobb/Jeans/7.jpeg'
import j30 from '../../Assets/men/Cobb/Jeans/8.jpeg'
import j31 from '../../Assets/men/Cobb/Jeans/9.jpeg'
import j32 from '../../Assets/men/Cobb/Jeans/10.jpeg'
import j33 from '../../Assets/men/Cobb/Jeans/11.jpeg'
import j34 from '../../Assets/men/Cobb/Jeans/12.jpeg'
import j35 from '../../Assets/men/Cobb/Jeans/13.jpeg'
import j36 from '../../Assets/men/Mufti/Jeans/1.jpeg'
import j37 from '../../Assets/men/Mufti/Jeans/2.jpeg'
import j38 from '../../Assets/men/Mufti/Jeans/3.jpeg'
import j39 from '../../Assets/men/Mufti/Jeans/4.jpeg'
import j40 from '../../Assets/men/Mufti/Jeans/5.jpeg'
import j41 from '../../Assets/men/Mufti/Jeans/6.jpeg'
import j42 from '../../Assets/men/Mufti/Jeans/7.jpeg'
import j43 from '../../Assets/men/Mufti/Jeans/8.jpeg'
import j44 from '../../Assets/men/Mufti/Jeans/9.jpeg'
import j45 from '../../Assets/men/Mufti/Jeans/10.jpeg'
import j46 from '../../Assets/men/Mufti/Jeans/11.jpeg'
import j47 from '../../Assets/men/Mufti/Jeans/12.jpeg'
import j48 from '../../Assets/men/Mufti/Jeans/13.jpeg'
import j49 from '../../Assets/men/Mufti/Jeans/14.jpeg'

let jeans_product=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j2,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j3,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j4,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j5,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j6,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j7,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j8,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j9,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j10,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j11,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j12,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j13,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j15,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j16,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j17,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j18,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j19,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j20,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j21,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j22,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j24,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j25,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j26,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j27,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j28,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j29,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j30,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j31,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j32,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:33,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j33,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:34,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j34,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:35,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j35,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:36,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j36,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:37,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j37,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:38,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j38,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:39,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j39,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:40,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j40,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:41,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j41,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:42,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j42,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:43,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j43,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:44,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j44,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:45,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j45,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:46,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j46,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:47,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j47,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:48,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j48,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:49,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j49,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },

]

export default jeans_product;