import l1 from '../../Assets/men/Allen Solly/Lower/1.jpeg'
import l2 from '../../Assets/men/Allen Solly/Lower/2.jpeg'
import l3 from '../../Assets/men/Allen Solly/Lower/3.jpeg'
import l4 from '../../Assets/men/Allen Solly/Lower/4.jpeg'
import l5 from '../../Assets/men/Allen Solly/Lower/5.jpeg'
import l6 from '../../Assets/men/Allen Solly/Lower/6.jpeg'
import l7 from '../../Assets/men/Allen Solly/Lower/7.jpeg'
import l8 from '../../Assets/men/Allen Solly/Lower/8.jpeg'
import l9 from '../../Assets/men/Allen Solly/Lower/9.jpeg'
import l10 from '../../Assets/men/Allen Solly/Lower/10.jpeg'
import l11 from '../../Assets/men/Allen Solly/Lower/11.jpeg'
import l12 from '../../Assets/men/Allen Solly/Lower/12.jpeg'
import l13 from '../../Assets/men/Peter England/Lower/1.jpeg'
import l14 from '../../Assets/men/Peter England/Lower/2.jpeg'
import l15 from '../../Assets/men/Peter England/Lower/3.jpeg'
import l16 from '../../Assets/men/Peter England/Lower/4.jpeg'
import l17 from '../../Assets/men/Peter England/Lower/5.jpeg'
import l18 from '../../Assets/men/Peter England/Lower/6.jpeg'
import l19 from '../../Assets/men/Peter England/Lower/7.jpeg'
import l20 from '../../Assets/men/Peter England/Lower/8.jpeg'
import l21 from '../../Assets/men/Peter England/Lower/9.jpeg'
import l22 from '../../Assets/men/Peter England/Lower/10.jpeg'
import l23 from '../../Assets/men/Cobb/Lower/1.jpeg'
import l24 from '../../Assets/men/Cobb/Lower/2.jpeg'
import l25 from '../../Assets/men/Cobb/Lower/3.jpeg'
import l26 from '../../Assets/men/Cobb/Lower/4.jpeg'
import l27 from '../../Assets/men/Cobb/Lower/5.jpeg'
import l28 from '../../Assets/men/Cobb/Lower/6.jpeg'
import l29 from '../../Assets/men/Cobb/Lower/7.jpeg'
import l30 from '../../Assets/men/Cobb/Lower/8.jpeg'
import l31 from '../../Assets/men/Cobb/Lower/9.jpeg'
import l32 from '../../Assets/men/Cobb/Lower/10.jpeg'
import l33 from '../../Assets/men/Cobb/Lower/11.jpeg'
import l34 from '../../Assets/men/Cobb/Lower/12.jpeg'
import l35 from '../../Assets/men/Cobb/Lower/13.jpeg'
import l36 from '../../Assets/men/Nike/Lower/1.jpeg'
import l37 from '../../Assets/men/Nike/Lower/2.jpeg'
import l38 from '../../Assets/men/Nike/Lower/3.jpeg'
import l39 from '../../Assets/men/Nike/Lower/4.jpeg'
import l40 from '../../Assets/men/Nike/Lower/5.jpeg'
import l41 from '../../Assets/men/Nike/Lower/6.jpeg'
import l42 from '../../Assets/men/Nike/Lower/7.jpeg'
import l43 from '../../Assets/men/Nike/Lower/8.jpeg'
import l44 from '../../Assets/men/Nike/Lower/9.jpeg'
import l45 from '../../Assets/men/Mufti/Lower/1.jpeg'
import l46 from '../../Assets/men/Mufti/Lower/2.jpeg'
import l47 from '../../Assets/men/Mufti/Lower/3.jpeg'
import l48 from '../../Assets/men/Mufti/Lower/4.jpeg'
import l49 from '../../Assets/men/Mufti/Lower/5.jpeg'

let lower_product=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l2,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l3,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l4,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 ", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l5,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l6,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l7,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 ", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l8,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l9,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l10,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l11,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Solid Track Pants",
        image:l12,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l13,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l14,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l15,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 ",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l16,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l17,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l18,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l19,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l20,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l21,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Solid Track Pants",
        image:l22,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l23,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l24,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l25,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l26,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l27,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l28,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l29,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l30,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l31,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l32,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:33,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l33,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:34,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l34,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:35,
        brand:"Cobb Italy",
        name:"Men Solid Track Pants",
        image:l35,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:36,
        brand:"Nike",
        name:"Men Solid Track Pants",
        image:l36,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:37,
        brand:"Nike",
        name:"Men Solid Track Pants",
        image:l37,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:38,
        brand:"Nike",
        name:"Men Solid Track Pants",
        image:l38,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:39,
        brand:"Nike",
        name:"Men Solid Track Pants",
        image:l39,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:40,
        brand:"Nike",
        name:"Men Solid Track Pants",
        image:l40,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:41,
        brand:"Nike",
        name:"Men Solid Track Pants",
        image:l41,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:42,
        brand:"Nike",
        name:"Men Solid Track Pants",
        image:l42,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:43,
        brand:"Nike",
        name:"Men Solid Track Pants",
        image:l43,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:44,
        brand:"Nike",
        name:"Men Solid Track Pants",
        image:l44,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:45,
        brand:"Mufti",
        name:"Men Solid Track Pants",
        image:l45,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:46,
        brand:"Mufti",
        name:"Men Solid Track Pants",
        image:l46,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:47,
        brand:"Mufti",
        name:"Men Solid Track Pants",
        image:l47,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:48,
        brand:"Mufti",
        name:"Men Solid Track Pants",
        image:l48,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:49,
        brand:"Mufti",
        name:"Men Solid Track Pants",
        image:l49,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },

]

export default lower_product