import p1 from '../../Assets/men/Allen Solly/Pant/1.jpeg'
import p2 from '../../Assets/men/Allen Solly/Pant/2.jpeg'
import p3 from '../../Assets/men/Allen Solly/Pant/3.jpeg'
import p4 from '../../Assets/men/Allen Solly/Pant/4.jpeg'
import p5 from '../../Assets/men/Allen Solly/Pant/5.jpeg'
import p6 from '../../Assets/men/Allen Solly/Pant/6.jpeg'
import p7 from '../../Assets/men/Allen Solly/Pant/7.jpeg'
import p8 from '../../Assets/men/Allen Solly/Pant/8.jpeg'
import p9 from '../../Assets/men/Allen Solly/Pant/9.jpeg'
import p10 from '../../Assets/men/Allen Solly/Pant/10.jpeg'
import p11 from '../../Assets/men/Allen Solly/Pant/11.jpeg'
import p12 from '../../Assets/men/Allen Solly/Pant/12.jpeg'
import p13 from '../../Assets/men/Peter England/Pant/1.jpeg'
import p14 from '../../Assets/men/Peter England/Pant/2.jpeg'
import p15 from '../../Assets/men/Peter England/Pant/3.jpeg'
import p16 from '../../Assets/men/Peter England/Pant/4.jpeg'
import p17 from '../../Assets/men/Peter England/Pant/5.jpeg'
import p18 from '../../Assets/men/Peter England/Pant/6.jpeg'
import p19 from '../../Assets/men/Peter England/Pant/7.jpeg'
import p20 from '../../Assets/men/Peter England/Pant/8.jpeg'
import p21 from '../../Assets/men/Peter England/Pant/9.jpeg'
import p22 from '../../Assets/men/Peter England/Pant/10.jpeg'
import p23 from '../../Assets/men/Cobb/Pant/1.jpg'
import p24 from '../../Assets/men/Cobb/Pant/2.jpg'
import p25 from '../../Assets/men/Cobb/Pant/3.jpg'
import p26 from '../../Assets/men/Cobb/Pant/4.jpg'
import p27 from '../../Assets/men/Cobb/Pant/5.jpg'
import p28 from '../../Assets/men/Cobb/Pant/6.jpg'
import p29 from '../../Assets/men/Cobb/Pant/7.jpg'
import p30 from '../../Assets/men/Cobb/Pant/8.jpg'
import p31 from '../../Assets/men/Cobb/Pant/9.jpg'
import p32 from '../../Assets/men/Cobb/Pant/10.jpg'
import p33 from '../../Assets/men/Cobb/Pant/11.jpg'
import p34 from '../../Assets/men/Cobb/Pant/12.jpg'
import p35 from '../../Assets/men/Cobb/Pant/13.jpg'
import p36 from '../../Assets/men/Mufti/Pant/1.jpeg'
import p37 from '../../Assets/men/Mufti/Pant/2.jpeg'
import p38 from '../../Assets/men/Mufti/Pant/3.jpeg'
import p39 from '../../Assets/men/Mufti/Pant/4.jpeg'
import p40 from '../../Assets/men/Mufti/Pant/5.jpeg'
import p41 from '../../Assets/men/Mufti/Pant/6.jpeg'
import p42 from '../../Assets/men/Mufti/Pant/7.jpeg'
import p43 from '../../Assets/men/Mufti/Pant/8.jpeg'
import p44 from '../../Assets/men/Mufti/Pant/9.jpeg'
import p45 from '../../Assets/men/Mufti/Pant/10.jpeg'
import p46 from '../../Assets/men/Mufti/Pant/11.jpeg'
import p47 from '../../Assets/men/Mufti/Pant/12.jpeg'
import p48 from '../../Assets/men/Mufti/Pant/13.jpeg'
import p49 from '../../Assets/men/Mufti/Pant/14.jpeg'

let pant_product=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p1,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p2,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p3,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p4,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p5,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p6,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p7,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p8,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p9,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p10,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p11,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p12,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p13,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p14,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p15,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p16,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p17,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p18,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p19,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p20,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p21,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p22,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p23,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p24,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p25,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p26,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p27,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p28,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p29,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p30,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p31,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p32,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:33,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p33,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:34,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p34,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:35,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p35,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:36,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p36,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:37,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p37,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:38,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p38,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:39,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p39,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:40,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p40,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:41,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p41,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:42,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p42,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:43,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p43,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:44,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p44,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:45,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p45,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:46,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p46,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:47,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p47,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:48,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p48,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:49,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p49,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },

]

export default pant_product;