

let sherwani_product=[
    {
        id:1,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh1,
        new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh2,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh3,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh4,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh5,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh6,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh7,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh8,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh9,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh10,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh11,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh12,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh13,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh14,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    // {
    //     id:15,
    //     brand:"Sherwani",
    //     name:"Sleeve Solid Sherwani",
    //     image:sh15,
    //     new_price:"₹1379",
    //     old_price:"₹2299",
    //     offer:"40% off",
    //     rating:"4.3★",
    //     review:1256,
    //     size:"M , L , XL",
    // },
    {
        id:16,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh16,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh17,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh18,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh19,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh20,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh21,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh22,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh23,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh24,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh25,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh26,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh27,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh28,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh29,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh30,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh31,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh32,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh33,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh34,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:35,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh35,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:36,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh36,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:37,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh37,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:38,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh38,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:39,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh39,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:40,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh40,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:41,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh41,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:42,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh42,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:43,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh43,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:44,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh44,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:45,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh45,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:46,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh46,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:47,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh47,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:48,
        brand:"Sherwani",
        name:"Sleeve Solid Sherwani",
        image:sh48,
       new_price:"₹2599",
        old_price:"₹3099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]

export default sherwani_product