import ts1 from '../../Assets/men/Allen Solly/T-shirt/1.jpeg'
import ts2 from '../../Assets/men/Allen Solly/T-shirt/2.jpeg'
import ts3 from '../../Assets/men/Allen Solly/T-shirt/3.jpeg'
import ts4 from '../../Assets/men/Allen Solly/T-shirt/4.jpeg'
import ts5 from '../../Assets/men/Allen Solly/T-shirt/5.jpeg'
import ts6 from '../../Assets/men/Allen Solly/T-shirt/6.jpeg'
import ts7 from '../../Assets/men/Allen Solly/T-shirt/7.jpeg'
import ts8 from '../../Assets/men/Allen Solly/T-shirt/8.jpeg'
import ts9 from '../../Assets/men/Allen Solly/T-shirt/9.jpeg'
import ts10 from '../../Assets/men/Allen Solly/T-shirt/10.jpeg'
import ts11 from '../../Assets/men/Allen Solly/T-shirt/11.jpeg'
import ts12 from '../../Assets/men/Allen Solly/T-shirt/12.jpeg'
import ts13 from '../../Assets/men/Peter England/T-shirt/1.jpeg'
import ts14 from '../../Assets/men/Peter England/T-shirt/2.jpeg'
import ts15 from '../../Assets/men/Peter England/T-shirt/3.jpeg'
import ts16 from '../../Assets/men/Peter England/T-shirt/4.jpeg'
import ts17 from '../../Assets/men/Peter England/T-shirt/5.jpeg'
import ts18 from '../../Assets/men/Peter England/T-shirt/6.jpeg'
import ts19 from '../../Assets/men/Peter England/T-shirt/7.jpeg'
import ts20 from '../../Assets/men/Peter England/T-shirt/8.jpeg'
import ts21 from '../../Assets/men/Peter England/T-shirt/9.jpeg'
import ts22 from '../../Assets/men/Peter England/T-shirt/10.jpeg'
import ts23 from '../../Assets/men/Cobb/T-shirt/1.jpeg'
import ts24 from '../../Assets/men/Cobb/T-shirt/2.jpeg'
import ts25 from '../../Assets/men/Cobb/T-shirt/3.jpeg'
import ts26 from '../../Assets/men/Cobb/T-shirt/4.jpeg'
import ts27 from '../../Assets/men/Cobb/T-shirt/5.jpeg'
import ts28 from '../../Assets/men/Cobb/T-shirt/6.jpeg'
import ts29 from '../../Assets/men/Cobb/T-shirt/7.jpeg'
import ts30 from '../../Assets/men/Cobb/T-shirt/8.jpeg'
import ts31 from '../../Assets/men/Cobb/T-shirt/9.jpeg'
import ts32 from '../../Assets/men/Cobb/T-shirt/10.jpeg'
import ts33 from '../../Assets/men/Adidas/T-shirt/1.jpeg'
import ts34 from '../../Assets/men/Adidas/T-shirt/2.jpeg'
import ts35 from '../../Assets/men/Adidas/T-shirt/3.jpeg'
import ts36 from '../../Assets/men/Adidas/T-shirt/4.jpeg'
import ts37 from '../../Assets/men/Adidas/T-shirt/5.jpeg'
import ts38 from '../../Assets/men/Adidas/T-shirt/6.jpeg'
import ts39 from '../../Assets/men/Adidas/T-shirt/7.jpeg'
import ts40 from '../../Assets/men/Adidas/T-shirt/8.jpeg'
import ts41 from '../../Assets/men/Adidas/T-shirt/9.jpeg'
import ts42 from '../../Assets/men/Adidas/T-shirt/10.jpeg'
import ts43 from '../../Assets/men/Adidas/T-shirt/11.jpeg'
import ts44 from '../../Assets/men/Mufti/T-shirt/1.jpeg'
import ts45 from '../../Assets/men/Mufti/T-shirt/2.jpeg'
import ts46 from '../../Assets/men/Mufti/T-shirt/3.jpeg'
import ts47 from '../../Assets/men/Mufti/T-shirt/4.jpeg'
import ts48 from '../../Assets/men/Mufti/T-shirt/5.jpeg'
import ts49 from '../../Assets/men/Mufti/T-shirt/6.jpeg'
import ts50 from '../../Assets/men/Mufti/T-shirt/7.jpeg'
import ts51 from '../../Assets/men/Mufti/T-shirt/8.jpeg'
import ts52 from '../../Assets/men/Mufti/T-shirt/9.jpeg'
import ts53 from '../../Assets/men/Mufti/T-shirt/10.jpeg'
import ts54 from '../../Assets/men/Nike/T-shirt/1.jpg'
import ts55 from '../../Assets/men/Nike/T-shirt/2.jpg'
import ts56 from '../../Assets/men/Nike/T-shirt/3.jpg'
import ts57 from '../../Assets/men/Nike/T-shirt/4.jpg'
import ts58 from '../../Assets/men/Nike/T-shirt/5.jpg'
import ts59 from '../../Assets/men/Nike/T-shirt/6.jpg'
import ts60 from '../../Assets/men/Nike/T-shirt/7.jpg'

let tshirt_product=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts2,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts3,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts4,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts5,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts6,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts7,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts8,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts9,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts10,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts11,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:ts12,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts14,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts15,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts16,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts17,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts18,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts19,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts20,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts21,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:ts22,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts24,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts25,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts26,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts27,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts28,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts29,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts30,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts31,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts32,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts33,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts34,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:35,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:ts35,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:36,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts36,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:37,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts37,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:38,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts38,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:39,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts39,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:40,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts40,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:41,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts41,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:42,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts42,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:43,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts43,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:44,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts44,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:45,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts45,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:46,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts46,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:47,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts47,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:48,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts48,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:49,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts49,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:50,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts50,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:51,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts51,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:52,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts52,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:53,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:ts53,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:54,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts54,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:55,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts55,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:56,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts56,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:57,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts57,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:58,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts58,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:59,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts59,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:60,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:ts60,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]

export default tshirt_product