import s1 from '../../Assets/men/Allen Solly/Shirt/1.jpeg'
import s2 from '../../Assets/men/Allen Solly/Shirt/2.jpeg'
import s3 from '../../Assets/men/Allen Solly/Shirt/3.jpeg'
import s4 from '../../Assets/men/Allen Solly/Shirt/4.jpeg'
import s5 from '../../Assets/men/Allen Solly/Shirt/5.jpeg'
import s6 from '../../Assets/men/Allen Solly/Shirt/6.jpeg'
import s7 from '../../Assets/men/Allen Solly/Shirt/7.jpeg'
import s8 from '../../Assets/men/Allen Solly/Shirt/8.jpeg'
import s9 from '../../Assets/men/Allen Solly/Shirt/9.jpeg'
import s10 from '../../Assets/men/Allen Solly/Shirt/10.jpeg'
import s11 from '../../Assets/men/Allen Solly/Shirt/11.jpeg'
import s12 from '../../Assets/men/Allen Solly/Shirt/12.jpeg'
import s13 from '../../Assets/men/Peter England/Shirt/1.jpeg'
import s14 from '../../Assets/men/Peter England/Shirt/2.jpg'
import s15 from '../../Assets/men/Peter England/Shirt/3.jpg'
import s16 from '../../Assets/men/Peter England/Shirt/4.jpeg'
import s17 from '../../Assets/men/Peter England/Shirt/5.jpeg'
import s18 from '../../Assets/men/Peter England/Shirt/6.jpeg'
import s19 from '../../Assets/men/Peter England/Shirt/7.jpeg'
import s20 from '../../Assets/men/Peter England/Shirt/8.jpeg'
import s21 from '../../Assets/men/Peter England/Shirt/9.jpeg'
import s22 from '../../Assets/men/Peter England/Shirt/10.jpeg'
import s23 from '../../Assets/men/Cobb/Shirt/1.jpg'
import s24 from '../../Assets/men/Cobb/Shirt/2.jpg'
import s25 from '../../Assets/men/Cobb/Shirt/3.jpg'
import s26 from '../../Assets/men/Cobb/Shirt/4.jpg'
import s27 from '../../Assets/men/Cobb/Shirt/5.jpg'
import s28 from '../../Assets/men/Cobb/Shirt/6.jpg'
import s29 from '../../Assets/men/Cobb/Shirt/7.jpg'
import s30 from '../../Assets/men/Cobb/Shirt/8.jpg'
import s31 from '../../Assets/men/Cobb/Shirt/9.jpg'
import s32 from '../../Assets/men/Cobb/Shirt/10.jpg'
import s33 from '../../Assets/men/Cobb/Shirt/11.jpg'
import s34 from '../../Assets/men/Cobb/Shirt/12.jpg'
import s35 from '../../Assets/men/Cobb/Shirt/13.jpg'
import s36 from '../../Assets/men/Cobb/Shirt/14.jpg'
import s37 from '../../Assets/men/Cobb/Shirt/15.jpg'
import s38 from '../../Assets/men/Cobb/Shirt/16.jpg'
import s39 from '../../Assets/men/Cobb/Shirt/17.jpg'
import s40 from '../../Assets/men/Mufti/Shirt/10.jpg'
import s41 from '../../Assets/men/Mufti/Shirt/9.jpg'
import s42 from '../../Assets/men/Mufti/Shirt/7.jpg'
import s43 from '../../Assets/men/Mufti/Shirt/8.jpg'
import s44 from '../../Assets/men/Mufti/Shirt/1.jpg'
import s45 from '../../Assets/men/Mufti/Shirt/2.jpg'
import s46 from '../../Assets/men/Mufti/Shirt/3.jpg'
import s47 from '../../Assets/men/Mufti/Shirt/4.jpg'
import s48 from '../../Assets/men/Mufti/Shirt/5.jpg'
import s49 from '../../Assets/men/Mufti/Shirt/6.jpg'

let shirt_product=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s2,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s3,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s4,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s5,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s6,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s7,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s8,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s9,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s10,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s11,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:s12,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s14,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s15,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s16,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s17,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s18,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s19,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s20,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s21,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:s22,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s24,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s25,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s26,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s27,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s28,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s29,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s30,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s31,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s32,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s33,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s34,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:35,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:s35,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:36,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:s36,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:37,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:s37,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:38,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:s38,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:39,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:s39,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:40,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:s40,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:41,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:s41,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:42,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:s42,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:43,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:s43,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:44,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:s44,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:45,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:s45,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:46,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:s46,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:47,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:s47,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:48,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:s48,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:49,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:s49,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]

export default shirt_product