import op1 from '../../Assets/women/One-Piece/1.jpeg'
import op2 from '../../Assets/women/One-Piece/2.jpeg'
import op3 from '../../Assets/women/One-Piece/3.jpeg'
import op4 from '../../Assets/women/One-Piece/4.jpeg'
import op5 from '../../Assets/women/One-Piece/5.jpeg'
import op6 from '../../Assets/women/One-Piece/6.jpeg'
import op7 from '../../Assets/women/One-Piece/7.jpeg'
import op8 from '../../Assets/women/One-Piece/8.jpeg'
import op9 from '../../Assets/women/One-Piece/9.jpeg'
import op10 from '../../Assets/women/One-Piece/10.jpeg'
import op11 from '../../Assets/women/One-Piece/11.jpeg'
import op12 from '../../Assets/women/One-Piece/12.jpeg'
import op13 from '../../Assets/women/One-Piece/13.jpeg'
import op14 from '../../Assets/women/One-Piece/14.jpeg'
import op15 from '../../Assets/women/One-Piece/15.jpeg'
import op16 from '../../Assets/women/One-Piece/16.jpeg'
import op17 from '../../Assets/women/One-Piece/17.jpeg'
import op18 from '../../Assets/women/One-Piece/18.jpeg'
import op19 from '../../Assets/women/One-Piece/19.jpeg'
import op20 from '../../Assets/women/One-Piece/20.jpeg'
import op21 from '../../Assets/women/One-Piece/21.jpeg'
import op22 from '../../Assets/women/One-Piece/22.jpeg'
import op23 from '../../Assets/women/One-Piece/23.jpeg'
import op24 from '../../Assets/women/One-Piece/24.jpeg'
import op25 from '../../Assets/women/One-Piece/25.jpeg'
import op26 from '../../Assets/women/One-Piece/26.jpeg'
import op27 from '../../Assets/women/One-Piece/27.jpeg'
import op28 from '../../Assets/women/One-Piece/28.jpeg'
import op29 from '../../Assets/women/One-Piece/29.jpeg'
import op30 from '../../Assets/women/One-Piece/30.jpeg'
import op31 from '../../Assets/women/One-Piece/31.jpeg'
import op32 from '../../Assets/women/One-Piece/32.jpeg'
import op33 from '../../Assets/women/One-Piece/33.jpeg'
import op34 from '../../Assets/women/One-Piece/34.jpeg'

let onePiece_product=[
    {
        id:1,
        name:"Women One Piece dress",
        image:op1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women One Piece dress",
        image:op2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women One Piece dress",
        image:op3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women One Piece dress",
        image:op4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women One Piece dress",
        image:op5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women One Piece dress",
        image:op6,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women One Piece dress",
        image:op7,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women One Piece dress",
        image:op8,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women One Piece dress",
        image:op9,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women One Piece dress",
        image:op10,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women One Piece dress",
        image:op11,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women One Piece dress",
        image:op12,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women One Piece dress",
        image:op13,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women One Piece dress",
        image:op14,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women One Piece dress",
        image:op15,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women One Piece dress",
        image:op16,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women One Piece dress",
        image:op17,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women One Piece dress",
        image:op18,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women One Piece dress",
        image:op19,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women One Piece dress",
        image:op20,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women One Piece dress",
        image:op21,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women One Piece dress",
        image:op22,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women One Piece dress",
        image:op23,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Women One Piece dress",
        image:op24,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Women One Piece dress",
        image:op25,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        name:"Women One Piece dress",
        image:op26,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        name:"Women One Piece dress",
        image:op27,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        name:"Women One Piece dress",
        image:op28,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        name:"Women One Piece dress",
        image:op29,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        name:"Women One Piece dress",
        image:op30,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        name:"Women One Piece dress",
        image:op31,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        name:"Women One Piece dress",
        image:op32,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        name:"Women One Piece dress",
        image:op33,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        name:"Women One Piece dress",
        image:op34,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export default onePiece_product;