import ss1 from '../../Assets/women/Salwar-Suit/1.jpeg'
import ss2 from '../../Assets/women/Salwar-Suit/2.jpeg'
import ss3 from '../../Assets/women/Salwar-Suit/3.jpeg'
import ss4 from '../../Assets/women/Salwar-Suit/4.jpeg'
import ss5 from '../../Assets/women/Salwar-Suit/5.jpeg'
import ss6 from '../../Assets/women/Salwar-Suit/6.jpeg'
import ss7 from '../../Assets/women/Salwar-Suit/7.jpeg'
import ss8 from '../../Assets/women/Salwar-Suit/8.jpeg'
import ss9 from '../../Assets/women/Salwar-Suit/9.jpeg'
import ss10 from '../../Assets/women/Salwar-Suit/10.jpeg'
import ss11 from '../../Assets/women/Salwar-Suit/11.jpeg'
import ss12 from '../../Assets/women/Salwar-Suit/12.jpeg'
import ss13 from '../../Assets/women/Salwar-Suit/13.jpeg'
import ss14 from '../../Assets/women/Salwar-Suit/14.jpeg'
import ss15 from '../../Assets/women/Salwar-Suit/15.jpeg'
import ss16 from '../../Assets/women/Salwar-Suit/16.jpeg'
import ss17 from '../../Assets/women/Salwar-Suit/17.jpeg'
import ss18 from '../../Assets/women/Salwar-Suit/18.jpeg'
import ss19 from '../../Assets/women/Salwar-Suit/19.jpeg'
import ss20 from '../../Assets/women/Salwar-Suit/20.jpeg'
import ss21 from '../../Assets/women/Salwar-Suit/21.jpeg'
import ss22 from '../../Assets/women/Salwar-Suit/22.jpeg'
import ss23 from '../../Assets/women/Salwar-Suit/23.jpeg'
import ss24 from '../../Assets/women/Salwar-Suit/24.jpeg'

let suitSalwar_product=[
    {
        id:1,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss6,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss7,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss8,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss9,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss10,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss11,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss12,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss13,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss14,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss15,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss16,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss17,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss18,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss19,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss20,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss21,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss22,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss23,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss24,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export default suitSalwar_product;