import h1 from '../Assets/men/Hoodie/h1.jpeg'
import h2 from '../Assets/men/Hoodie/h2.jpeg'
import h3 from '../Assets/men/Hoodie/h3.jpeg'
import h4 from '../Assets/men/Hoodie/h4.jpeg'
import h5 from '../Assets/men/Hoodie/h5.jpeg'
import h6 from '../Assets/men/Hoodie/h6.jpeg'
import h7 from '../Assets/men/Hoodie/h7.jpeg'
import h8 from '../Assets/men/Hoodie/h8.jpeg'
import h9 from '../Assets/men/Hoodie/h9.jpeg'
import h10 from '../Assets/men/Hoodie/h10.jpeg'
import h11 from '../Assets/men/Hoodie/h11.jpeg'
import h12 from '../Assets/men/Hoodie/h12.jpeg'
import h13 from '../Assets/men/Hoodie/h13.jpeg'
import h14 from '../Assets/men/Hoodie/h14.jpeg'
import h15 from '../Assets/men/Hoodie/h15.jpeg'
import h16 from '../Assets/men/Hoodie/h16.jpeg'
import h17 from '../Assets/men/Hoodie/h17.jpeg'
import h18 from '../Assets/men/Hoodie/h18.jpeg'
import h19 from '../Assets/men/Hoodie/h19.jpeg'
import h20 from '../Assets/men/Hoodie/h20.jpeg'
import h21 from '../Assets/men/Hoodie/h21.jpeg'
import h22 from '../Assets/men/Hoodie/h22.jpeg'
import h23 from '../Assets/men/Hoodie/h23.jpeg'
import h24 from '../Assets/men/Hoodie/h24.jpeg'
import h25 from '../Assets/men/Hoodie/h25.jpeg'
import h26 from '../Assets/men/Hoodie/h26.jpeg'
import h27 from '../Assets/men/Hoodie/h27.jpeg'
import h28 from '../Assets/men/Hoodie/h28.jpeg'
import h29 from '../Assets/men/Hoodie/h29.jpeg'
import h30 from '../Assets/men/Hoodie/h30.jpeg'
import h31 from '../Assets/men/Hoodie/h31.jpeg'
import h32 from '../Assets/men/Hoodie/h32.jpeg'
import h33 from '../Assets/men/Hoodie/h33.jpeg'
import h34 from '../Assets/men/Hoodie/h34.jpeg'
import h35 from '../Assets/men/Hoodie/h35.jpeg'
import h36 from '../Assets/men/Hoodie/h36.jpeg'
import h37 from '../Assets/men/Hoodie/h37.jpeg'
import h38 from '../Assets/men/Hoodie/h38.jpeg'
import h39 from '../Assets/men/Hoodie/h39.jpeg'
import h40 from '../Assets/men/Hoodie/h40.jpeg'
import h41 from '../Assets/men/Hoodie/h41.jpeg'
import h42 from '../Assets/men/Hoodie/h42.jpeg'
import h43 from '../Assets/men/Hoodie/h43.jpg'
import h44 from '../Assets/men/Hoodie/h44.jpg'
// jeans
import j1 from '../Assets/men/Jeans/1.jpeg'
import j2 from '../Assets/men/Jeans/2.jpeg'
import j3 from '../Assets/men/Jeans/3.jpeg'
import j4 from '../Assets/men/Jeans/4.jpeg'
import j5 from '../Assets/men/Jeans/5.jpeg'
import j6 from '../Assets/men/Jeans/6.jpeg'
import j7 from '../Assets/men/Jeans/7.jpeg'
import j8 from '../Assets/men/Jeans/8.jpeg'
import j9 from '../Assets/men/Jeans/9.jpeg'
import j10 from '../Assets/men/Jeans/10.jpeg'
import j11 from '../Assets/men/Jeans/11.jpeg'
import j12 from '../Assets/men/Jeans/12.jpeg'
import j13 from '../Assets/men/Jeans/13.jpeg'
import j14 from '../Assets/men/Jeans/14.jpeg'
import j15 from '../Assets/men/Jeans/15.jpeg'
import j16 from '../Assets/men/Jeans/16.jpeg'
import j17 from '../Assets/men/Jeans/17.jpeg'
import j18 from '../Assets/men/Jeans/18.jpeg'
import j19 from '../Assets/men/Jeans/19.jpeg'
import j20 from '../Assets/men/Jeans/20.jpeg'
import j21 from '../Assets/men/Jeans/21.jpeg'
import j22 from '../Assets/men/Jeans/22.jpeg'
import j23 from '../Assets/men/Jeans/23.jpeg'
import j24 from '../Assets/men/Jeans/24.jpeg'
import j25 from '../Assets/men/Jeans/25.jpeg'
import j26 from '../Assets/men/Jeans/26.jpeg'
import j27 from '../Assets/men/Jeans/27.jpeg'
import j28 from '../Assets/men/Jeans/28.jpeg'
import j29 from '../Assets/men/Jeans/29.jpeg'
import j30 from '../Assets/men/Jeans/30.jpeg'
import j31 from '../Assets/men/Jeans/31.jpeg'
import j32 from '../Assets/men/Jeans/32.jpeg'
import j33 from '../Assets/men/Jeans/33.jpeg'
import j34 from '../Assets/men/Jeans/34.jpeg'
import j35 from '../Assets/men/Jeans/35.jpeg'
import j36 from '../Assets/men/Jeans/36.jpeg'
import j37 from '../Assets/men/Jeans/37.jpeg'
import j38 from '../Assets/men/Jeans/38.jpeg'
import j39 from '../Assets/men/Jeans/39.jpeg'
import j40 from '../Assets/men/Jeans/40.jpeg'
// pant
import p1 from '../Assets/men/Pant/1.jpeg'
import p2 from '../Assets/men/Pant/2.jpeg'
import p3 from '../Assets/men/Pant/3.jpeg'
import p4 from '../Assets/men/Pant/4.jpeg'
import p5 from '../Assets/men/Pant/5.jpeg'
import p6 from '../Assets/men/Pant/6.jpeg'
import p7 from '../Assets/men/Pant/7.jpeg'
import p8 from '../Assets/men/Pant/8.jpeg'
import p9 from '../Assets/men/Pant/9.jpeg'
import p10 from '../Assets/men/Pant/10.jpeg'
import p11 from '../Assets/men/Pant/11.jpeg'
import p12 from '../Assets/men/Pant/12.jpeg'
import p13 from '../Assets/men/Pant/13.jpeg'
import p14 from '../Assets/men/Pant/14.jpeg'
import p15 from '../Assets/men/Pant/15.jpeg'
import p16 from '../Assets/men/Pant/16.jpeg'
import p17 from '../Assets/men/Pant/17.jpeg'
import p18 from '../Assets/men/Pant/18.jpeg'
import p19 from '../Assets/men/Pant/19.jpeg'
import p20 from '../Assets/men/Pant/20.jpeg'
import p21 from '../Assets/men/Pant/21.jpeg'
import p22 from '../Assets/men/Pant/22.jpeg'
import p23 from '../Assets/men/Pant/23.jpg'
import p24 from '../Assets/men/Pant/24.jpg'
import p25 from '../Assets/men/Pant/25.jpg'
import p26 from '../Assets/men/Pant/26.jpg'
import p27 from '../Assets/men/Pant/27.jpg'
import p28 from '../Assets/men/Pant/28.jpg'
import p29 from '../Assets/men/Pant/29.jpg'
import p30 from '../Assets/men/Pant/30.jpg'
import p31 from '../Assets/men/Pant/31.jpg'
import p32 from '../Assets/men/Pant/32.jpeg'
import p33 from '../Assets/men/Pant/33.jpeg'
import p34 from '../Assets/men/Pant/34.jpeg'
import p35 from '../Assets/men/Pant/35.jpeg'
import p36 from '../Assets/men/Pant/36.jpeg'
import p37 from '../Assets/men/Pant/37.jpeg'
import p38 from '../Assets/men/Pant/38.jpeg'
import p39 from '../Assets/men/Pant/39.jpeg'


// lower
import t1 from '../Assets/men/Track_pant/1.jpeg'
import t2 from '../Assets/men/Track_pant/2.jpeg'
import t3 from '../Assets/men/Track_pant/3.jpeg'
import t4 from '../Assets/men/Track_pant/4.jpeg'
import t5 from '../Assets/men/Track_pant/5.jpeg'
import t6 from '../Assets/men/Track_pant/6.jpeg'
import t7 from '../Assets/men/Track_pant/7.jpeg'
import t8 from '../Assets/men/Track_pant/8.jpeg'
import t9 from '../Assets/men/Track_pant/9.jpeg'
import t10 from '../Assets/men/Track_pant/10.jpeg'
import t11 from '../Assets/men/Track_pant/11.jpeg'
import t12 from '../Assets/men/Track_pant/12.jpeg'
import t13 from '../Assets/men/Track_pant/13.jpeg'
import t14 from '../Assets/men/Track_pant/14.jpeg'
import t15 from '../Assets/men/Track_pant/15.jpeg'
import t16 from '../Assets/men/Track_pant/16.jpeg'
import t17 from '../Assets/men/Track_pant/17.jpeg'
import t18 from '../Assets/men/Track_pant/18.jpeg'
import t19 from '../Assets/men/Track_pant/19.jpeg'
import t20 from '../Assets/men/Track_pant/20.jpeg'
import t21 from '../Assets/men/Track_pant/21.jpeg'
import t22 from '../Assets/men/Track_pant/22.jpeg'
import t23 from '../Assets/men/Track_pant/23.jpeg'
import t24 from '../Assets/men/Track_pant/24.jpeg'
import t25 from '../Assets/men/Track_pant/25.jpeg'
import t26 from '../Assets/men/Track_pant/26.jpeg'
import t27 from '../Assets/men/Track_pant/27.jpeg'
import t28 from '../Assets/men/Track_pant/28.jpeg'
import t29 from '../Assets/men/Track_pant/29.jpeg'
import t30 from '../Assets/men/Track_pant/30.jpeg'
import t31 from '../Assets/men/Track_pant/31.jpeg'
import t32 from '../Assets/men/Track_pant/32.jpeg'
import t33 from '../Assets/men/Track_pant/33.jpeg'
import t34 from '../Assets/men/Track_pant/34.jpeg'
import t35 from '../Assets/men/Track_pant/35.jpeg'
import t36 from '../Assets/men/Track_pant/36.jpeg'
// Shirt
import srt1 from '../Assets/men/Shirt/1.jpeg'
import srt2 from '../Assets/men/Shirt/2.jpeg'
import srt3 from '../Assets/men/Shirt/3.jpeg'
import srt4 from '../Assets/men/Shirt/4.jpeg'
import srt5 from '../Assets/men/Shirt/5.jpeg'
import srt6 from '../Assets/men/Shirt/6.jpeg'
import srt7 from '../Assets/men/Shirt/7.jpeg'
import srt8 from '../Assets/men/Shirt/8.jpeg'
import srt9 from '../Assets/men/Shirt/9.jpeg'
import srt10 from '../Assets/men/Shirt/10.jpeg'
import srt11 from '../Assets/men/Shirt/11.jpeg'
import srt12 from '../Assets/men/Shirt/12.jpeg'
import srt13 from '../Assets/men/Shirt/13.jpeg'
import srt14 from '../Assets/men/Shirt/14.jpeg'
import srt15 from '../Assets/men/Shirt/15.jpeg'
import srt16 from '../Assets/men/Shirt/16.jpg'
import srt17 from '../Assets/men/Shirt/17.jpg'
import srt18 from '../Assets/men/Shirt/18.jpg'
import srt19 from '../Assets/men/Shirt/19.jpg'
import srt20 from '../Assets/men/Shirt/20.jpg'
import srt21 from '../Assets/men/Shirt/21.jpg'
import srt22 from '../Assets/men/Shirt/22.jpg'
import srt23 from '../Assets/men/Shirt/23.jpg'
import srt24 from '../Assets/men/Shirt/24.jpg'
import srt25 from '../Assets/men/Shirt/25.jpg'
import srt26 from '../Assets/men/Shirt/26.jpg'
import srt27 from '../Assets/men/Shirt/27.jpg'
import srt28 from '../Assets/men/Shirt/28.jpg'
import srt29 from '../Assets/men/Shirt/29.jpg'
import srt30 from '../Assets/men/Shirt/30.jpg'
// t-shirt
import tsm1 from '../Assets/men/T_shirt/1.jpeg'
import tsm2 from  '../Assets/men/T_shirt/2.jpeg'
import tsm3 from '../Assets/men/T_shirt/3.jpeg'
import tsm4 from '../Assets/men/T_shirt/4.jpeg'
import tsm5 from '../Assets/men/T_shirt/5.jpeg'
import tsm6 from '../Assets/men/T_shirt/6.jpeg'
import tsm7 from '../Assets/men/T_shirt/7.jpeg'
import tsm8 from '../Assets/men/T_shirt/8.jpeg'
import tsm9 from '../Assets/men/T_shirt/9.jpeg'
import tsm10 from '../Assets/men/T_shirt/10.jpeg'
import tsm11 from '../Assets/men/T_shirt/11.jpeg'
import tsm12 from '../Assets/men/T_shirt/12.jpeg'
import tsm13 from '../Assets/men/T_shirt/13.jpeg'
import tsm14 from '../Assets/men/T_shirt/14.jpeg'
import tsm15 from '../Assets/men/T_shirt/15.jpeg'
import tsm16 from '../Assets/men/T_shirt/16.jpeg'
import tsm17 from '../Assets/men/T_shirt/17.jpeg'
import tsm18 from '../Assets/men/T_shirt/18.jpeg'
import tsm19 from '../Assets/men/T_shirt/19.jpeg'
import tsm20 from '../Assets/men/T_shirt/20.jpeg'
import tsm21 from '../Assets/men/T_shirt/21.jpeg'
import tsm22 from '../Assets/men/T_shirt/22.jpeg'
import tsm23 from '../Assets/men/T_shirt/23.jpeg'
import tsm24 from '../Assets/men/T_shirt/24.jpeg'
import tsm25 from '../Assets/men/T_shirt/25.jpeg'
import tsm26 from '../Assets/men/T_shirt/26.jpeg'
import tsm27 from '../Assets/men/T_shirt/27.jpeg'
import tsm28 from '../Assets/men/T_shirt/28.jpeg'
import tsm29 from '../Assets/men/T_shirt/29.jpeg'
import tsm30 from '../Assets/men/T_shirt/30.jpeg'
import tsm31 from '../Assets/men/T_shirt/31.jpeg'
import tsm32 from '../Assets/men/T_shirt/32.jpeg'
import tsm33 from '../Assets/men/T_shirt/33.jpg'
import tsm34 from '../Assets/men/T_shirt/34.jpg'
import tsm35 from '../Assets/men/T_shirt/35.jpg'
import tsm36 from '../Assets/men/T_shirt/36.jpg'
import tsm37 from '../Assets/men/T_shirt/37.jpg'

// Shervani
// import sh1 from '....//men/Sherwani/1.jpeg'
// import sh2 from '....//men/Sherwani/2.jpeg'
// import sh3 from '....//men/Sherwani/3.jpeg'
// import sh4 from '....//men/Sherwani/4.jpeg'
// import sh5 from '....//men/Sherwani/5.jpeg'
// import sh6 from '....//men/Sherwani/6.jpeg'
// import sh7 from '....//men/Sherwani/7.jpeg'
// import sh8 from '....//men/Sherwani/8.jpeg'
// import sh9 from '....//men/Sherwani/9.jpeg'
// import sh10 from '....//men/Sherwani/10.jpeg'
// import sh11 from '....//men/Sherwani/11.jpeg'
// import sh12 from '....//men/Sherwani/12.jpeg'
// import sh13 from '....//men/Sherwani/13.jpeg'
// import sh14 from '....//men/Sherwani/14.jpeg'
// import sh15 from '....//men/Sherwani/15.jpeg'
// import sh16 from '....//men/Sherwani/16.jpeg'
// import sh17 from '....//men/Sherwani/17.jpeg'
// import sh18 from '....//men/Sherwani/18.jpeg'
// import sh19 from '....//men/Sherwani/19.jpeg'
// import sh20 from '....//men/Sherwani/20.jpeg'
// import sh21 from '....//men/Sherwani/21.jpeg'
// import sh22 from '....//men/Sherwani/22.jpeg'
// import sh23 from '....//men/Sherwani/23.jpeg'
// import sh24 from '....//men/Sherwani/24.jpeg'
// import sh25 from '....//men/Sherwani/25.jpeg'
// import sh26 from '....//men/Sherwani/26.jpeg'

// Coat-Pant

// Hoodie
let hoodie=[
   {
        id:1,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
   {
        id:14,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:38,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h38,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
      {
        id:44,
        brand:"Mufti",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h44,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {hoodie}

let allHoodie=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h2,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h3,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h4,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h5,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h6,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h7,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h8,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h9,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h10,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h11,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h12,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h13,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h15,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h16,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h17,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h18,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h19,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h20,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h20,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h21,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h22,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h24,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h25,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h26,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h27,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h28,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h29,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h30,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h31,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h32,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h33,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h34,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:35,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h35,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:36,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h36,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:37,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h37,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:38,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h38,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:39,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h39,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:40,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h40,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:41,
        brand:"Mufti",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h41,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:42,
        brand:"Mufti",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h42,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:43,
        brand:"Mufti",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h43,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:44,
        brand:"Mufti",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h44,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allHoodie}
// Jeans
let jeans=[
      {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j2,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
       {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
   {
        id:36,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j36,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
   {
        id:27,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j27,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
]
export {jeans}

let allJeans=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j2,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j3,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j4,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j5,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j6,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j7,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j8,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j9,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j10,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j11,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j12,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j13,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j15,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j16,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j17,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j18,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j19,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j20,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j21,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j22,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j24,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j25,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j26,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j27,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j28,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j29,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j30,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j31,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j32,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:33,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j33,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:34,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j34,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:35,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j35,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:36,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j36,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:37,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j37,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:38,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j38,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:39,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j39,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:40,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j40,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
]
export {allJeans}
// Pant
let pant=[
       {
        id:1,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p1,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
      {
        id:13,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p13,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p23,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
     {
        id:36,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p36,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
      {
        id:24,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p24,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
]
export {pant}

let allPant=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p1,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p2,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p3,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p4,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p5,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p6,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p7,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p8,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p9,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p10,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p11,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p12,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p13,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p14,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p15,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p16,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p17,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p18,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p19,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p20,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p21,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p22,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p23,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p24,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p25,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p26,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p27,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p28,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p29,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p30,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p31,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p32,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:33,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p33,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:34,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p34,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:35,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p35,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:36,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p36,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:37,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p37,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:38,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p38,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:39,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p39,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },

]
export {allPant}
// Lower
let lower=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
      {
        id:13,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t13,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
      {
        id:23,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t23,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
   {
        id:36,
        brand:"Nike",
        name:"Men Solid Track-Pants",
        image:t36,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
      {
        id:24,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t24,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
]
export {lower}

let allLower=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t2,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t3,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t4,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 ", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t5,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t6,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t7,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 ", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t8,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t9,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t10,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t11,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t12,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t13,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t14,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t15,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 ",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t16,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t17,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t18,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t19,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t20,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t21,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t22,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t23,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t24,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t25,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t26,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t27,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t28,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t29,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t30,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t31,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t32,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:33,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t33,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:34,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t34,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:35,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t35,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:36,
        brand:"Nike",
        name:"Men Solid Track-Pants",
        image:t36,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
]
export {allLower}
// Shirt
let shirt=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt29,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt30,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {shirt}

let allShirt=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt2,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt3,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt4,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt5,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt6,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt7,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt8,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt9,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt10,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt11,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt12,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt14,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt15,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:16,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt16,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt17,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt18,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt19,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt20,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt21,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt22,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt24,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt25,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt26,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt27,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt28,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt29,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt30,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allShirt}
// T-Shirt
let t_shirt=[
  {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
   {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
      {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
         {
        id:30,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm30,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
           {
        id:36,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:tsm36,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {t_shirt}

let allT_shirt=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm2,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm3,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm4,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm5,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm6,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm7,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm8,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm9,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm10,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm11,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm12,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm14,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm15,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm16,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm17,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm18,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm19,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm20,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm21,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm22,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm24,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm25,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm26,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm27,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm28,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm29,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm30,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm31,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm32,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:tsm33,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:tsm34,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:35,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:tsm35,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:36,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:tsm36,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:37,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:tsm37,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allT_shirt}