// Hoodie
import h1 from '../Assets/men/Hoodie/1.png'
import h2 from '../Assets/men/Hoodie/2.png'
import h3 from '../Assets/men/Hoodie/3.png'
import h4 from '../Assets/men/Hoodie/4.png'
import h5 from '../Assets/men/Hoodie/5.png'
import h6 from '../Assets/men/Hoodie/6.png'
import h7 from '../Assets/men/Hoodie/7.png'
import h8 from '../Assets/men/Hoodie/8.png'
import h9 from '../Assets/men/Hoodie/9.png'
import h10 from '../Assets/men/Hoodie/10.png'
import h11 from '../Assets/men/Hoodie/11.png'
import h12 from '../Assets/men/Hoodie/12.png'
import h13 from '../Assets/men/Hoodie/13.png'
import h14 from '../Assets/men/Hoodie/14.png'
import h15 from '../Assets/men/Hoodie/15.png'
import h16 from '../Assets/men/Hoodie/16.png'
import h17 from '../Assets/men/Hoodie/17.png'
import h18 from '../Assets/men/Hoodie/18.png'
import h19 from '../Assets/men/Hoodie/19.png'
import h20 from '../Assets/men/Hoodie/20.png'
import h21 from '../Assets/men/Hoodie/21.png'
import h22 from '../Assets/men/Hoodie/22.png'
import h23 from '../Assets/men/Hoodie/23.png'
import h24 from '../Assets/men/Hoodie/24.png'
import h25 from '../Assets/men/Hoodie/25.png'
import h26 from '../Assets/men/Hoodie/26.png'
import h27 from '../Assets/men/Hoodie/27.png'
import h28 from '../Assets/men/Hoodie/28.png'
import h29 from '../Assets/men/Hoodie/29.png'
import h30 from '../Assets/men/Hoodie/30.png'
import h31 from '../Assets/men/Hoodie/31.png'
import h32 from '../Assets/men/Hoodie/32.png'
import h33 from '../Assets/men/Hoodie/33.png'
import h34 from '../Assets/men/Hoodie/34.png'
import h35 from '../Assets/men/Hoodie/35.png'
import h36 from '../Assets/men/Hoodie/36.png'
import h37 from '../Assets/men/Hoodie/37.png'
import h38 from '../Assets/men/Hoodie/38.png'
import h39 from '../Assets/men/Hoodie/39.png'
import h40 from '../Assets/men/Hoodie/40.png'
// jeans
import j1 from '../Assets/men/Jeans/1.png'
import j2 from '../Assets/men/Jeans/2.png'
import j3 from '../Assets/men/Jeans/3.png'
import j4 from '../Assets/men/Jeans/4.png'
import j5 from '../Assets/men/Jeans/5.png'
import j6 from '../Assets/men/Jeans/6.png'
import j7 from '../Assets/men/Jeans/7.png'
import j8 from '../Assets/men/Jeans/8.png'
import j9 from '../Assets/men/Jeans/9.png'
import j10 from '../Assets/men/Jeans/10.png'
import j11 from '../Assets/men/Jeans/11.png'
import j12 from '../Assets/men/Jeans/12.png'
import j13 from '../Assets/men/Jeans/13.png'
import j14 from '../Assets/men/Jeans/14.png'
import j15 from '../Assets/men/Jeans/15.png'
import j16 from '../Assets/men/Jeans/16.png'
import j17 from '../Assets/men/Jeans/17.png'
import j18 from '../Assets/men/Jeans/18.png'
import j19 from '../Assets/men/Jeans/19.png'
import j20 from '../Assets/men/Jeans/20.png'
import j21 from '../Assets/men/Jeans/21.png'
import j22 from '../Assets/men/Jeans/22.png'
import j23 from '../Assets/men/Jeans/23.png'
import j24 from '../Assets/men/Jeans/24.png'
import j25 from '../Assets/men/Jeans/25.png'
import j26 from '../Assets/men/Jeans/26.png'
import j27 from '../Assets/men/Jeans/27.png'
import j28 from '../Assets/men/Jeans/28.png'
import j29 from '../Assets/men/Jeans/29.png'
import j30 from '../Assets/men/Jeans/30.png'
// pant
import p1 from '../Assets/men/Pant/1.png'
import p2 from '../Assets/men/Pant/2.png'
import p3 from '../Assets/men/Pant/3.png'
import p4 from '../Assets/men/Pant/4.png'
import p5 from '../Assets/men/Pant/5.png'
import p6 from '../Assets/men/Pant/6.png'
import p7 from '../Assets/men/Pant/7.png'
import p8 from '../Assets/men/Pant/8.png'
import p9 from '../Assets/men/Pant/9.png'
import p10 from '../Assets/men/Pant/10.png'
import p11 from '../Assets/men/Pant/11.png'
import p12 from '../Assets/men/Pant/12.png'
import p13 from '../Assets/men/Pant/13.png'
import p14 from '../Assets/men/Pant/14.png'
import p15 from '../Assets/men/Pant/15.png'
import p16 from '../Assets/men/Pant/16.png'
import p17 from '../Assets/men/Pant/17.png'
import p18 from '../Assets/men/Pant/18.png'
import p19 from '../Assets/men/Pant/19.png'
import p20 from '../Assets/men/Pant/20.png'
import p21 from '../Assets/men/Pant/21.png'
import p22 from '../Assets/men/Pant/22.png'
import p23 from '../Assets/men/Pant/23.png'
import p24 from '../Assets/men/Pant/24.png'
import p25 from '../Assets/men/Pant/25.png'
// lower
import t1 from '../Assets/men/Track_pant/1.png'
import t2 from '../Assets/men/Track_pant/2.png'
import t3 from '../Assets/men/Track_pant/3.png'
import t4 from '../Assets/men/Track_pant/4.png'
import t5 from '../Assets/men/Track_pant/5.png'
import t6 from '../Assets/men/Track_pant/6.png'
import t7 from '../Assets/men/Track_pant/7.png'
import t8 from '../Assets/men/Track_pant/8.png'
import t9 from '../Assets/men/Track_pant/9.png'
import t10 from '../Assets/men/Track_pant/10.png'
import t11 from '../Assets/men/Track_pant/11.png'
import t12 from '../Assets/men/Track_pant/12.png'
import t13 from '../Assets/men/Track_pant/13.png'
import t14 from '../Assets/men/Track_pant/14.png'
import t15 from '../Assets/men/Track_pant/15.png'
import t16 from '../Assets/men/Track_pant/16.png'
import t17 from '../Assets/men/Track_pant/17.png'
import t18 from '../Assets/men/Track_pant/18.png'
import t19 from '../Assets/men/Track_pant/19.png'
import t20 from '../Assets/men/Track_pant/20.png'
import t21 from '../Assets/men/Track_pant/21.png'
import t22 from '../Assets/men/Track_pant/22.png'
import t23 from '../Assets/men/Track_pant/23.png'
import t24 from '../Assets/men/Track_pant/24.png'
import t25 from '../Assets/men/Track_pant/25.png'
// Shirt
import srt1 from '../Assets/men/Shirt/1.png'
import srt2 from '../Assets/men/Shirt/2.png'
import srt3 from '../Assets/men/Shirt/3.png'
import srt4 from '../Assets/men/Shirt/4.png'
import srt5 from '../Assets/men/Shirt/5.png'
import srt6 from '../Assets/men/Shirt/6.png'
import srt7 from '../Assets/men/Shirt/7.png'
import srt8 from '../Assets/men/Shirt/8.png'
import srt9 from '../Assets/men/Shirt/9.png'
import srt10 from '../Assets/men/Shirt/10.png'
import srt11 from '../Assets/men/Shirt/11.png'
import srt12 from '../Assets/men/Shirt/12.png'
import srt13 from '../Assets/men/Shirt/13.png'
import srt14 from '../Assets/men/Shirt/14.png'
import srt15 from '../Assets/men/Shirt/15.png'
import srt16 from '../Assets/men/Shirt/16.png'
import srt17 from '../Assets/men/Shirt/17.png'
import srt18 from '../Assets/men/Shirt/18.png'
import srt19 from '../Assets/men/Shirt/19.png'
import srt20 from '../Assets/men/Shirt/20.png'
import srt21 from '../Assets/men/Shirt/21.png'
import srt22 from '../Assets/men/Shirt/22.png'
import srt23 from '../Assets/men/Shirt/23.png'
import srt24 from '../Assets/men/Shirt/24.png'
import srt25 from '../Assets/men/Shirt/25.png'
import srt26 from '../Assets/men/Shirt/26.png'
import srt27 from '../Assets/men/Shirt/27.png'
import srt28 from '../Assets/men/Shirt/28.png'
import srt29 from '../Assets/men/Shirt/29.png'
// t-shirt
import tsm1 from '../Assets/men/T_shirt/1.png'
import tsm2 from  '../Assets/men/T_shirt/2.png'
import tsm3 from '../Assets/men/T_shirt/3.png'
import tsm4 from '../Assets/men/T_shirt/4.png'
import tsm5 from '../Assets/men/T_shirt/5.png'
import tsm6 from '../Assets/men/T_shirt/6.png'
import tsm7 from '../Assets/men/T_shirt/7.png'
import tsm8 from '../Assets/men/T_shirt/8.png'
import tsm9 from '../Assets/men/T_shirt/9.png'
import tsm10 from '../Assets/men/T_shirt/10.png'
import tsm11 from '../Assets/men/T_shirt/11.png'
import tsm12 from '../Assets/men/T_shirt/12.png'
import tsm13 from '../Assets/men/T_shirt/13.png'
import tsm14 from '../Assets/men/T_shirt/14.png'
import tsm15 from '../Assets/men/T_shirt/15.png'
import tsm16 from '../Assets/men/T_shirt/16.png'
import tsm17 from '../Assets/men/T_shirt/17.png'
import tsm18 from '../Assets/men/T_shirt/18.png'
import tsm19 from '../Assets/men/T_shirt/19.png'
import tsm20 from '../Assets/men/T_shirt/20.png'
import tsm21 from '../Assets/men/T_shirt/21.png'
import tsm22 from '../Assets/men/T_shirt/22.png'
import tsm23 from '../Assets/men/T_shirt/23.png'
import tsm24 from '../Assets/men/T_shirt/24.png'
import tsm25 from '../Assets/men/T_shirt/25.png'
import tsm26 from '../Assets/men/T_shirt/26.png'
import tsm27 from '../Assets/men/T_shirt/27.png'
import tsm28 from '../Assets/men/T_shirt/28.png'
import tsm29 from '../Assets/men/T_shirt/29.png'
// Coat-Pant
import c1 from '../Assets/men/Coat_pant/1.png'
import c2 from '../Assets/men/Coat_pant/2.png'
import c3 from '../Assets/men/Coat_pant/3.png'
import c4 from '../Assets/men/Coat_pant/4.png'
import c5 from '../Assets/men/Coat_pant/5.png'
import c6 from '../Assets/men/Coat_pant/6.png'
import c7 from '../Assets/men/Coat_pant/7.png'
import c8 from '../Assets/men/Coat_pant/8.png'
import c9 from '../Assets/men/Coat_pant/9.png'
import c10 from '../Assets/men/Coat_pant/10.png'
import c11 from '../Assets/men/Coat_pant/11.png'
import c12 from '../Assets/men/Coat_pant/12.png'
import c13 from '../Assets/men/Coat_pant/13.png'
import c14 from '../Assets/men/Coat_pant/14.png'
import c15 from '../Assets/men/Coat_pant/15.png'
import c16 from '../Assets/men/Coat_pant/16.png'
import c17 from '../Assets/men/Coat_pant/17.png'
import c18 from '../Assets/men/Coat_pant/18.png'
import c19 from '../Assets/men/Coat_pant/19.png'
import c20 from '../Assets/men/Coat_pant/20.png'
import c21 from '../Assets/men/Coat_pant/21.png'
import c22 from '../Assets/men/Coat_pant/22.png'
import c23 from '../Assets/men/Coat_pant/23.png'
import c24 from '../Assets/men/Coat_pant/24.png'
import c25 from '../Assets/men/Coat_pant/25.png'

// Hoodie
let hoodie=[
   {
        id:1,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
   {
        id:14,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:38,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h38,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
     {
        id:40,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h40,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {hoodie}

let allHoodie=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h2,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h3,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h4,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h5,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h6,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h7,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h8,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h9,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h10,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h11,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h12,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h13,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h15,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h16,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h17,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h18,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h19,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h20,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h20,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h21,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h22,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h24,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h25,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h26,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h27,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h28,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h29,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h30,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h31,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        brand:"Cobb Italy",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h32,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h33,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h34,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:35,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h35,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:36,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h36,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:37,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h37,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:38,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h38,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:39,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h39,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:40,
        brand:"Nike",
        name:"Men Full Sleeve Solid Hooded Sweatshirt",
        image:h40,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allHoodie}
// Jeans
let jeans=[
      {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j2,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
       {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
   {
        id:30,
        brand:"Mufti",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j30,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
   {
        id:27,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j27,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
]
export {jeans}

let allJeans=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j1,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j2,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j3,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j4,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j5,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j6,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j7,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j8,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j9,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j10,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j11,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j12,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j13,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j14,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j15,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j16,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j17,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j18,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j19,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j20,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j21,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j22,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j23,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j24,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j25,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j26,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:27,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j27,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:28,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j28,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:29,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j29,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:30,
        brand:"Cobb Italy",
        name:"Men Slim Mid Rise Dark Jeans",
        image:j30,
        new_price:"₹1379",
        old_price:"₹2299",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
]
export {allJeans}
// Pant
let pant=[
       {
        id:1,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p1,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
      {
        id:13,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p13,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p23,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
     {
        id:25,
        brand:"Mufti",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p25,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
      {
        id:24,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p24,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
]
export {pant}

let allPant=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p1,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p2,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p3,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p4,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p5,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p6,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p7,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p8,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p9,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p10,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p11,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p12,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p13,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p14,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p15,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 , 36",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p16,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p17,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p18,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p19,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p20,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p21,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p22,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p23,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p24,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Regular Fit Cotton Blend Trousers",
        image:p25,
        new_price:"₹1199",
        old_price:"₹1399",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 , 36",
    },
]
export {allPant}
// Lower
let lower=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
      {
        id:13,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t13,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
      {
        id:23,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t23,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
   {
        id:25,
        brand:"Nike",
        name:"Men Solid Track-Pants",
        image:t25,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
      {
        id:24,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t24,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
]
export {lower}

let allLower=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t2,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t3,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t4,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 ", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t5,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t6,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t7,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 ", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t8,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t9,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t10,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:11,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t11,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:12,
        brand:"Allen Solly",
        name:"Men Solid Track-Pants",
        image:t12,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t13,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t14,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t15,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256,
        size:"30 , 32 , 34 ",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t16,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t17,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t18,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:19,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t19,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:20,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t20,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:21,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t21,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:22,
        brand:"Peter England",
        name:"Men Solid Track-Pants",
        image:t22,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t23,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t24,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Solid Track-Pants",
        image:t25,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"40% off",
        rating:"4.3★",
        review:1256, 
        size:"30 , 32 , 34 ",
    },
  
]
export {allLower}
// Shirt
let shirt=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt29,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt28,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {shirt}

let allShirt=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt2,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt3,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt4,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt5,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt6,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:srt7,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt8,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt9,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt10,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt11,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt12,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt14,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:srt15,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:16,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt16,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt17,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt18,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt19,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt20,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt21,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt22,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:srt24,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt25,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt26,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt27,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt28,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:srt29,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allShirt}
// T-Shirt
let t_shirt=[
  {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
   {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
      {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
         {
        id:28,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm28,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
           {
        id:29,
        brand:"Nike",
        name:"Men Slim Fit Solid Shirt",
        image:tsm29,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {t_shirt}

let allT_shirt=[
    {
        id:1,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm1,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm2,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm3,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm4,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm5,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm6,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm7,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm8,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm9,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        brand:"Allen Solly",
        name:"Men Slim Fit Solid Shirt",
        image:tsm10,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm11,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm12,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm13,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:14,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm14,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm15,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:16,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm16,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm17,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        brand:"Peter England",
        name:"Men Slim Fit Solid Shirt",
        image:tsm18,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm19,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm20,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm21,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm22,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm23,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm24,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm25,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        brand:"Cobb Italy",
        name:"Men Slim Fit Solid Shirt",
        image:tsm26,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm27,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm28,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        brand:"Mufti",
        name:"Men Slim Fit Solid Shirt",
        image:tsm29,
        new_price:"₹1499",
        old_price:"₹1699",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {allT_shirt}
// Coat-Pant
let coat_Pant=[
     {
        id:1,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:tsm1,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:2,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:tsm1,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:3,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:tsm1,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:4,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:tsm1,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:5,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:tsm1,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },

]
export {coat_Pant}

let allCoat_Pant=[
     {
        id:1,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c1,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:2,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c2,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:3,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c3,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:4,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c4,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:5,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c5,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
    {
        id:6,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c6,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:7,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c7,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:8,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c8,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:9,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c9,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:10,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c10,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
 {
        id:11,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c11,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:12,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c12,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:13,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c13,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:14,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c14,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:15,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c15,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
 {
        id:16,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c16,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:17,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c17,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:18,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c18,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:19,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c19,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:20,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c20,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
 {
        id:21,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c21,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:22,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c22,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:23,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c23,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:24,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c24,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },
     {
        id:25,
        brand:"METRONAUT",
        name:"Men 3 piece suit for men Solid Suit",
        image:c25,
        new_price:"₹4499",
        old_price:"₹4999",
        offer:"12% off",
        rating:"4.3★",
        review:1256, 
        size:"36 , 38 , 40",
    },

]
export {allCoat_Pant}