// Lahenga
import l1 from '../Assets/women/Lehenga/1.png'
import l2 from '../Assets/women/Lehenga/2.png'
import l3 from '../Assets/women/Lehenga/3.png'
import l4 from '../Assets/women/Lehenga/4.png'
import l5 from '../Assets/women/Lehenga/5.png'
import l6 from '../Assets/women/Lehenga/6.png'
import l7 from '../Assets/women/Lehenga/7.png'
import l8 from '../Assets/women/Lehenga/8.png'
import l9 from '../Assets/women/Lehenga/9.png'
import l10 from '../Assets/women/Lehenga/10.png'
import l11 from '../Assets/women/Lehenga/11.png'
import l12 from '../Assets/women/Lehenga/12.png'
import l13 from '../Assets/women/Lehenga/13.png'
import l14 from '../Assets/women/Lehenga/14.png'
import l15 from '../Assets/women/Lehenga/15.png'
import l16 from '../Assets/women/Lehenga/16.png'
import l17 from '../Assets/women/Lehenga/17.png'
import l18 from '../Assets/women/Lehenga/18.png'
import l19 from '../Assets/women/Lehenga/19.png'
import l20 from '../Assets/women/Lehenga/20.png'
import l21 from '../Assets/women/Lehenga/21.png'
import l22 from '../Assets/women/Lehenga/22.png'
import l23 from '../Assets/women/Lehenga/23.png'
import l24 from '../Assets/women/Lehenga/24.png'
import l25 from '../Assets/women/Lehenga/25.png'
// Gown
import g1 from '../Assets/women/Gown/1.png'
import g3 from '../Assets/women/Gown/3.png'
import g2 from '../Assets/women/Gown/2.png'
import g4 from '../Assets/women/Gown/4.png'
import g5 from '../Assets/women/Gown/5.png'
import g6 from '../Assets/women/Gown/6.png'
import g7 from '../Assets/women/Gown/7.png'
import g8 from '../Assets/women/Gown/8.png'
import g9 from '../Assets/women/Gown/9.png'
import g11 from '../Assets/women/Gown/11.png'
import g12 from '../Assets/women/Gown/12.png'
import g13 from '../Assets/women/Gown/13.png'
import g14 from '../Assets/women/Gown/14.png'
import g15 from '../Assets/women/Gown/15.png'
import g16 from '../Assets/women/Gown/16.png'
import g17 from '../Assets/women/Gown/17.png'
import g18 from '../Assets/women/Gown/18.png'
import g19 from '../Assets/women/Gown/19.png'
import g20 from '../Assets/women/Gown/20.png'
import g21 from '../Assets/women/Gown/21.png'
import g22 from '../Assets/women/Gown/22.png'
import g23 from '../Assets/women/Gown/23.png'
import g24 from '../Assets/women/Gown/24.png'
import g25 from '../Assets/women/Gown/25.png'
import g26 from '../Assets/women/Gown/26.png'

// One-Piece
import op1 from '../Assets/women/One_piece/1.png'
import op2 from '../Assets/women/One_piece/2.png'
import op3 from '../Assets/women/One_piece/3.png'
import op4 from '../Assets/women/One_piece/4.png'
import op5 from '../Assets/women/One_piece/5.png'
import op6 from '../Assets/women/One_piece/6.png'
import op7 from '../Assets/women/One_piece/7.png'
import op8 from '../Assets/women/One_piece/8.png'
import op9 from '../Assets/women/One_piece/9.png'
import op10 from '../Assets/women/One_piece/10.png'
import op11 from '../Assets/women/One_piece/11.png'
import op12 from '../Assets/women/One_piece/12.png'
import op13 from '../Assets/women/One_piece/13.png'
import op14 from '../Assets/women/One_piece/14.png'
import op15 from '../Assets/women/One_piece/15.png'
import op16 from '../Assets/women/One_piece/16.png'
import op17 from '../Assets/women/One_piece/17.png'
import op18 from '../Assets/women/One_piece/18.png'
import op19 from '../Assets/women/One_piece/19.png'
import op20 from '../Assets/women/One_piece/20.png'
import op21 from '../Assets/women/One_piece/21.png'
import op22 from '../Assets/women/One_piece/22.png'
import op23 from '../Assets/women/One_piece/23.png'
import op24 from '../Assets/women/One_piece/24.png'
import op25 from '../Assets/women/One_piece/25.png'
import op26 from '../Assets/women/One_piece/26.png'
import op27 from '../Assets/women/One_piece/27.png'
import op28 from '../Assets/women/One_piece/28.png'
import op29 from '../Assets/women/One_piece/29.png'
import op30 from '../Assets/women/One_piece/30.png'
import op31 from '../Assets/women/One_piece/31.png'
import op32 from '../Assets/women/One_piece/32.png'
import op33 from '../Assets/women/One_piece/33.png'
import op34 from '../Assets/women/One_piece/34.png'
// Salwar-Suit
import ss1 from '../Assets/women/Salwar_suit/1.png'
import ss2 from '../Assets/women/Salwar_suit/2.png'
import ss3 from '../Assets/women/Salwar_suit/3.png'
import ss4 from '../Assets/women/Salwar_suit/4.png'
import ss5 from '../Assets/women/Salwar_suit/5.png'
import ss6 from '../Assets/women/Salwar_suit/6.png'
import ss7 from '../Assets/women/Salwar_suit/7.png'
import ss8 from '../Assets/women/Salwar_suit/8.png'
import ss9 from '../Assets/women/Salwar_suit/9.png'
import ss10 from '../Assets/women/Salwar_suit/10.png'
import ss11 from '../Assets/women/Salwar_suit/11.png'
import ss12 from '../Assets/women/Salwar_suit/12.png'
import ss13 from '../Assets/women/Salwar_suit/13.png'
import ss14 from '../Assets/women/Salwar_suit/14.png'
import ss15 from '../Assets/women/Salwar_suit/15.png'
import ss16 from '../Assets/women/Salwar_suit/16.png'
import ss17 from '../Assets/women/Salwar_suit/17.png'
import ss18 from '../Assets/women/Salwar_suit/18.png'
import ss19 from '../Assets/women/Salwar_suit/19.png'
import ss20 from '../Assets/women/Salwar_suit/20.png'
import ss21 from '../Assets/women/Salwar_suit/21.png'
import ss22 from '../Assets/women/Salwar_suit/22.png'
import ss23 from '../Assets/women/Salwar_suit/23.png'
import ss24 from '../Assets/women/Salwar_suit/24.png'
// Suit
import s1 from '../Assets/women/Suit/1.png'
import s2 from '../Assets/women/Suit/2.png'
import s3 from '../Assets/women/Suit/3.png'
import s4 from '../Assets/women/Suit/4.png'
import s5 from '../Assets/women/Suit/5.png'
import s6 from '../Assets/women/Suit/6.png'
import s7 from '../Assets/women/Suit/7.png'
import s8 from '../Assets/women/Suit/8.png'
import s9 from '../Assets/women/Suit/9.png'
import s10 from '../Assets/women/Suit/10.png'
import s11 from '../Assets/women/Suit/11.png'
import s12 from '../Assets/women/Suit/12.png'
import s13 from '../Assets/women/Suit/13.png'
import s14 from '../Assets/women/Suit/14.png'
import s15 from '../Assets/women/Suit/15.png'
import s16 from '../Assets/women/Suit/16.png'
import s17 from '../Assets/women/Suit/17.png'
import s18 from '../Assets/women/Suit/18.png'
import s19 from '../Assets/women/Suit/19.png'
import s20 from '../Assets/women/Suit/20.png'
import s21 from '../Assets/women/Suit/21.png'
import s22 from '../Assets/women/Suit/22.png'
import s23 from '../Assets/women/Suit/23.png'
// T-shirt
import ts1 from '../Assets/women/t_shirt/1.png'
import ts2 from '../Assets/women/t_shirt/2.png'
import ts3 from '../Assets/women/t_shirt/3.png'
import ts4 from '../Assets/women/t_shirt/4.png'
import ts5 from '../Assets/women/t_shirt/5.png'
import ts6 from '../Assets/women/t_shirt/6.png'
import ts7 from '../Assets/women/t_shirt/7.png'
import ts8 from '../Assets/women/t_shirt/8.png'
import ts9 from '../Assets/women/t_shirt/9.png'
import ts10 from '../Assets/women/t_shirt/10.png'
import ts11 from '../Assets/women/t_shirt/11.png'
import ts12 from '../Assets/women/t_shirt/12.png'
import ts13 from '../Assets/women/t_shirt/13.png'
import ts14 from '../Assets/women/t_shirt/14.png'
import ts15 from '../Assets/women/t_shirt/15.png'
import ts16 from '../Assets/women/t_shirt/16.png'
import ts17 from '../Assets/women/t_shirt/17.png'
import ts18 from '../Assets/women/t_shirt/18.png'
import ts19 from '../Assets/women/t_shirt/19.png'
import ts20 from '../Assets/women/t_shirt/20.png'
import ts21 from '../Assets/women/t_shirt/21.png'
import ts22 from '../Assets/women/t_shirt/22.png'
import ts23 from '../Assets/women/t_shirt/23.png'
import ts24 from '../Assets/women/t_shirt/24.png'

// Lahenga
let lahenga=[
   {
        id:1,
        name:"Embroidered Semi Stitched Lehenga",
        image:l1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Embroidered Semi Stitched Lehenga",
        image:l2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Embroidered Semi Stitched Lehenga",
        image:l3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Embroidered Semi Stitched Lehenga",
        image:l4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Embroidered Semi Stitched Lehenga",
        image:l5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {lahenga};

let allLahenga=[
    {
        id:1,
        name:"Embroidered Semi Stitched Lehenga",
        image:l1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Embroidered Semi Stitched Lehenga",
        image:l2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Embroidered Semi Stitched Lehenga",
        image:l3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Embroidered Semi Stitched Lehenga",
        image:l4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Embroidered Semi Stitched Lehenga",
        image:l5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Embroidered Semi Stitched Lehenga",
        image:l6,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Embroidered Semi Stitched Lehenga",
        image:l7,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Embroidered Semi Stitched Lehenga",
        image:l8,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Embroidered Semi Stitched Lehenga",
        image:l9,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Embroidered Semi Stitched Lehenga",
        image:l10,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Embroidered Semi Stitched Lehenga",
        image:l11,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Embroidered Semi Stitched Lehenga",
        image:l12,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Embroidered Semi Stitched Lehenga",
        image:l13,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Embroidered Semi Stitched Lehenga",
        image:l14,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Embroidered Semi Stitched Lehenga",
        image:l15,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Embroidered Semi Stitched Lehenga",
        image:l16,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Embroidered Semi Stitched Lehenga",
        image:l17,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Embroidered Semi Stitched Lehenga",
        image:l18,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Embroidered Semi Stitched Lehenga",
        image:l19,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Embroidered Semi Stitched Lehenga",
        image:l20,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Embroidered Semi Stitched Lehenga",
        image:l21,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Embroidered Semi Stitched Lehenga",
        image:l22,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Embroidered Semi Stitched Lehenga",
        image:l23,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Embroidered Semi Stitched Lehenga",
        image:l24,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Embroidered Semi Stitched Lehenga",
        image:l25,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allLahenga}
// Gown
let gown=[
     {
        id:1,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {gown}

let allGown=[
    {
        id:1,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g6,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g7,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g8,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g9,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g11,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g12,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g13,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g14,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g15,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g16,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g17,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g18,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g19,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g20,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g21,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g22,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g23,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g24,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g25,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g26,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allGown}

// One-piece
let one_piece=[
    {
        id:1,
        name:"Women One Piece dress",
        image:op1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women One Piece dress",
        image:op2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women One Piece dress",
        image:op3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women One Piece dress",
        image:op4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women One Piece dress",
        image:op5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {one_piece}

let allOne_piece=[
    {
        id:1,
        name:"Women One Piece dress",
        image:op1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women One Piece dress",
        image:op2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women One Piece dress",
        image:op3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women One Piece dress",
        image:op4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women One Piece dress",
        image:op5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women One Piece dress",
        image:op6,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women One Piece dress",
        image:op7,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women One Piece dress",
        image:op8,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women One Piece dress",
        image:op9,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women One Piece dress",
        image:op10,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women One Piece dress",
        image:op11,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women One Piece dress",
        image:op12,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women One Piece dress",
        image:op13,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women One Piece dress",
        image:op14,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women One Piece dress",
        image:op15,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women One Piece dress",
        image:op16,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women One Piece dress",
        image:op17,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women One Piece dress",
        image:op18,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women One Piece dress",
        image:op19,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women One Piece dress",
        image:op20,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women One Piece dress",
        image:op21,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women One Piece dress",
        image:op22,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women One Piece dress",
        image:op23,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Women One Piece dress",
        image:op24,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Women One Piece dress",
        image:op25,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        name:"Women One Piece dress",
        image:op26,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        name:"Women One Piece dress",
        image:op27,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        name:"Women One Piece dress",
        image:op28,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        name:"Women One Piece dress",
        image:op29,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        name:"Women One Piece dress",
        image:op30,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        name:"Women One Piece dress",
        image:op31,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        name:"Women One Piece dress",
        image:op32,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        name:"Women One Piece dress",
        image:op33,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        name:"Women One Piece dress",
        image:op34,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allOne_piece}

// Suit-Salwar
let suit_salwar=[
     {
        id:1,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {suit_salwar}

let allSalwar_Suit=[
    {
        id:1,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss6,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss7,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss8,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss9,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss10,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss11,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss12,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss13,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss14,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss15,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss16,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss17,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss18,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss19,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss20,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss21,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss22,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss23,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss24,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allSalwar_Suit}
// Suit
let suit=[
       {
        id:1,
        name:"Women Coat Solid Suit",
        image:s1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Coat Solid Suit",
        image:s2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Coat Solid Suit",
        image:s3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Coat Solid Suit",
        image:s4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Coat Solid Suit",
        image:s5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {suit}

let allSuit=[
    {
        id:1,
        name:"Women Coat Solid Suit",
        image:s1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Coat Solid Suit",
        image:s2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Coat Solid Suit",
        image:s3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Coat Solid Suit",
        image:s4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Coat Solid Suit",
        image:s5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women Coat Solid Suit",
        image:s6,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women Coat Solid Suit",
        image:s7,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women Coat Solid Suit",
        image:s8,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women Coat Solid Suit",
        image:s9,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women Coat Solid Suit",
        image:s10,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women Coat Solid Suit",
        image:s11,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women Coat Solid Suit",
        image:s12,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women Coat Solid Suit",
        image:s13,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women Coat Solid Suit",
        image:s14,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women Coat Solid Suit",
        image:s15,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women Coat Solid Suit",
        image:s16,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women Coat Solid Suit",
        image:s17,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women Coat Solid Suit",
        image:s18,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women Coat Solid Suit",
        image:s19,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women Coat Solid Suit",
        image:s20,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women Coat Solid Suit",
        image:s21,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women Coat Solid Suit",
        image:s22,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women Coat Solid Suit",
        image:s23,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allSuit}

let tshirt=[
       {
        id:1,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts2,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts3,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts4,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts5,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {tshirt}

let allT_Shirt=[
    {
        id:1,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts2,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts3,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts4,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts5,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts6,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts7,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts8,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts9,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts10,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts11,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts12,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts13,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts14,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts15,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts16,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts17,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts18,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts19,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts20,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts21,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts22,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts23,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts24,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allT_Shirt}