// Lahenga
import l1 from '../Assets/women/Lehenga/1.jpeg'
import l2 from '../Assets/women/Lehenga/2.jpeg'
import l3 from '../Assets/women/Lehenga/3.jpeg'
import l4 from '../Assets/women/Lehenga/4.jpeg'
import l5 from '../Assets/women/Lehenga/5.jpeg'
import l6 from '../Assets/women/Lehenga/6.jpeg'
import l7 from '../Assets/women/Lehenga/7.jpeg'
import l8 from '../Assets/women/Lehenga/8.jpeg'
import l9 from '../Assets/women/Lehenga/9.jpeg'
import l10 from '../Assets/women/Lehenga/10.jpeg'
import l11 from '../Assets/women/Lehenga/11.jpeg'
import l12 from '../Assets/women/Lehenga/12.jpeg'
import l13 from '../Assets/women/Lehenga/13.jpeg'
import l14 from '../Assets/women/Lehenga/14.jpeg'
import l15 from '../Assets/women/Lehenga/15.jpeg'
import l16 from '../Assets/women/Lehenga/16.jpeg'
import l17 from '../Assets/women/Lehenga/17.jpeg'
import l18 from '../Assets/women/Lehenga/18.jpeg'
import l19 from '../Assets/women/Lehenga/19.jpeg'
import l20 from '../Assets/women/Lehenga/20.jpeg'
import l21 from '../Assets/women/Lehenga/21.jpeg'
import l22 from '../Assets/women/Lehenga/22.jpeg'
import l23 from '../Assets/women/Lehenga/23.jpeg'
import l24 from '../Assets/women/Lehenga/24.jpeg'
import l25 from '../Assets/women/Lehenga/25.jpeg'
// Gown
import g1 from '../Assets/women/Gown/1.jpeg'
import g2 from '../Assets/women/Gown/2.jpeg'
import g3 from '../Assets/women/Gown/3.jpeg'
import g4 from '../Assets/women/Gown/4.jpeg'
import g5 from '../Assets/women/Gown/5.jpeg'
import g6 from '../Assets/women/Gown/6.jpeg'
import g7 from '../Assets/women/Gown/7.jpeg'
import g8 from '../Assets/women/Gown/8.jpeg'
import g9 from '../Assets/women/Gown/9.jpeg'
import g11 from '../Assets/women/Gown/11.jpeg'
import g12 from '../Assets/women/Gown/12.jpeg'
import g13 from '../Assets/women/Gown/13.jpeg'
import g14 from '../Assets/women/Gown/14.jpeg'
import g15 from '../Assets/women/Gown/15.jpeg'
import g16 from '../Assets/women/Gown/16.jpeg'
import g17 from '../Assets/women/Gown/17.jpeg'
import g18 from '../Assets/women/Gown/18.jpeg'
import g19 from '../Assets/women/Gown/19.jpeg'
import g20 from '../Assets/women/Gown/20.jpeg'
import g21 from '../Assets/women/Gown/21.jpeg'
import g22 from '../Assets/women/Gown/22.jpeg'
import g23 from '../Assets/women/Gown/23.jpeg'
import g24 from '../Assets/women/Gown/24.jpeg'
import g25 from '../Assets/women/Gown/25.jpeg'
import g26 from '../Assets/women/Gown/26.jpeg'
import g27 from '../Assets/women/Gown/27.jpeg'
import g28 from '../Assets/women/Gown/28.jpeg'
import g29 from '../Assets/women/Gown/29.jpeg'
// One-Piece
import op1 from '../Assets/women/One-Piece/1.jpeg'
import op2 from '../Assets/women/One-Piece/2.jpeg'
import op3 from '../Assets/women/One-Piece/3.jpeg'
import op4 from '../Assets/women/One-Piece/4.jpeg'
import op5 from '../Assets/women/One-Piece/5.jpeg'
import op6 from '../Assets/women/One-Piece/6.jpeg'
import op7 from '../Assets/women/One-Piece/7.jpeg'
import op8 from '../Assets/women/One-Piece/8.jpeg'
import op9 from '../Assets/women/One-Piece/9.jpeg'
import op10 from '../Assets/women/One-Piece/10.jpeg'
import op11 from '../Assets/women/One-Piece/11.jpeg'
import op12 from '../Assets/women/One-Piece/12.jpeg'
import op13 from '../Assets/women/One-Piece/13.jpeg'
import op14 from '../Assets/women/One-Piece/14.jpeg'
import op15 from '../Assets/women/One-Piece/15.jpeg'
import op16 from '../Assets/women/One-Piece/16.jpeg'
import op17 from '../Assets/women/One-Piece/17.jpeg'
import op18 from '../Assets/women/One-Piece/18.jpeg'
import op19 from '../Assets/women/One-Piece/19.jpeg'
import op20 from '../Assets/women/One-Piece/20.jpeg'
import op21 from '../Assets/women/One-Piece/21.jpeg'
import op22 from '../Assets/women/One-Piece/22.jpeg'
import op23 from '../Assets/women/One-Piece/23.jpeg'
import op24 from '../Assets/women/One-Piece/24.jpeg'
import op25 from '../Assets/women/One-Piece/25.jpeg'
import op26 from '../Assets/women/One-Piece/26.jpeg'
import op27 from '../Assets/women/One-Piece/27.jpeg'
import op28 from '../Assets/women/One-Piece/28.jpeg'
import op29 from '../Assets/women/One-Piece/29.jpeg'
import op30 from '../Assets/women/One-Piece/30.jpeg'
import op31 from '../Assets/women/One-Piece/31.jpeg'
import op32 from '../Assets/women/One-Piece/32.jpeg'
import op33 from '../Assets/women/One-Piece/33.jpeg'
import op34 from '../Assets/women/One-Piece/34.jpeg'
// Salwar-Suit
import ss1 from '../Assets/women/Salwar-Suit/1.jpeg'
import ss2 from '../Assets/women/Salwar-Suit/2.jpeg'
import ss3 from '../Assets/women/Salwar-Suit/3.jpeg'
import ss4 from '../Assets/women/Salwar-Suit/4.jpeg'
import ss5 from '../Assets/women/Salwar-Suit/5.jpeg'
import ss6 from '../Assets/women/Salwar-Suit/6.jpeg'
import ss7 from '../Assets/women/Salwar-Suit/7.jpeg'
import ss8 from '../Assets/women/Salwar-Suit/8.jpeg'
import ss9 from '../Assets/women/Salwar-Suit/9.jpeg'
import ss10 from '../Assets/women/Salwar-Suit/10.jpeg'
import ss11 from '../Assets/women/Salwar-Suit/11.jpeg'
import ss12 from '../Assets/women/Salwar-Suit/12.jpeg'
import ss13 from '../Assets/women/Salwar-Suit/13.jpeg'
import ss14 from '../Assets/women/Salwar-Suit/14.jpeg'
import ss15 from '../Assets/women/Salwar-Suit/15.jpeg'
import ss16 from '../Assets/women/Salwar-Suit/16.jpeg'
import ss17 from '../Assets/women/Salwar-Suit/17.jpeg'
import ss18 from '../Assets/women/Salwar-Suit/18.jpeg'
import ss19 from '../Assets/women/Salwar-Suit/19.jpeg'
import ss20 from '../Assets/women/Salwar-Suit/20.jpeg'
import ss21 from '../Assets/women/Salwar-Suit/21.jpeg'
import ss22 from '../Assets/women/Salwar-Suit/22.jpeg'
import ss23 from '../Assets/women/Salwar-Suit/23.jpeg'
import ss24 from '../Assets/women/Salwar-Suit/24.jpeg'
// Suit
import s1 from '../Assets/women/Suit/1.jpeg'
import s2 from '../Assets/women/Suit/2.jpeg'
import s3 from '../Assets/women/Suit/3.jpeg'
import s4 from '../Assets/women/Suit/4.jpeg'
import s5 from '../Assets/women/Suit/5.jpeg'
import s6 from '../Assets/women/Suit/6.jpeg'
import s7 from '../Assets/women/Suit/7.jpeg'
import s8 from '../Assets/women/Suit/8.jpeg'
import s9 from '../Assets/women/Suit/9.jpeg'
import s10 from '../Assets/women/Suit/10.jpeg'
import s11 from '../Assets/women/Suit/11.jpeg'
import s12 from '../Assets/women/Suit/12.jpeg'
import s13 from '../Assets/women/Suit/13.jpeg'
import s14 from '../Assets/women/Suit/14.jpeg'
import s15 from '../Assets/women/Suit/15.jpeg'
import s16 from '../Assets/women/Suit/16.jpeg'
import s17 from '../Assets/women/Suit/17.jpeg'
import s18 from '../Assets/women/Suit/18.jpeg'
import s19 from '../Assets/women/Suit/19.jpeg'
import s20 from '../Assets/women/Suit/20.jpeg'
import s21 from '../Assets/women/Suit/21.jpeg'
import s22 from '../Assets/women/Suit/22.jpeg'
import s23 from '../Assets/women/Suit/23.jpeg'
// T-shirt
import ts1 from '../Assets/women/T-Shirt/1.jpeg'
import ts2 from '../Assets/women/T-Shirt/2.jpeg'
import ts3 from '../Assets/women/T-Shirt/3.jpeg'
import ts4 from '../Assets/women/T-Shirt/4.jpeg'
import ts5 from '../Assets/women/T-Shirt/5.jpeg'
import ts6 from '../Assets/women/T-Shirt/6.jpeg'
import ts7 from '../Assets/women/T-Shirt/7.jpeg'
import ts8 from '../Assets/women/T-Shirt/8.jpeg'
import ts9 from '../Assets/women/T-Shirt/9.jpeg'
import ts10 from '../Assets/women/T-Shirt/10.jpeg'
import ts11 from '../Assets/women/T-Shirt/11.jpeg'
import ts12 from '../Assets/women/T-Shirt/12.jpeg'
import ts13 from '../Assets/women/T-Shirt/13.jpeg'
import ts14 from '../Assets/women/T-Shirt/14.jpeg'
import ts15 from '../Assets/women/T-Shirt/15.jpeg'
import ts16 from '../Assets/women/T-Shirt/16.jpeg'
import ts17 from '../Assets/women/T-Shirt/17.jpeg'
import ts18 from '../Assets/women/T-Shirt/18.jpeg'
import ts19 from '../Assets/women/T-Shirt/19.jpeg'
import ts20 from '../Assets/women/T-Shirt/20.jpeg'
import ts21 from '../Assets/women/T-Shirt/21.jpeg'
import ts22 from '../Assets/women/T-Shirt/22.jpeg'
import ts23 from '../Assets/women/T-Shirt/23.jpeg'
import ts24 from '../Assets/women/T-Shirt/24.jpeg'
import ts25 from '../Assets/women/T-Shirt/25.jpeg'

// Lahenga
let lahenga=[
   {
        id:1,
        name:"Embroidered Semi Stitched Lehenga",
        image:l1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Embroidered Semi Stitched Lehenga",
        image:l2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Embroidered Semi Stitched Lehenga",
        image:l3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Embroidered Semi Stitched Lehenga",
        image:l4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Embroidered Semi Stitched Lehenga",
        image:l5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {lahenga};

let allLahenga=[
    {
        id:1,
        name:"Embroidered Semi Stitched Lehenga",
        image:l1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Embroidered Semi Stitched Lehenga",
        image:l2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Embroidered Semi Stitched Lehenga",
        image:l3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Embroidered Semi Stitched Lehenga",
        image:l4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Embroidered Semi Stitched Lehenga",
        image:l5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Embroidered Semi Stitched Lehenga",
        image:l6,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Embroidered Semi Stitched Lehenga",
        image:l7,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Embroidered Semi Stitched Lehenga",
        image:l8,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Embroidered Semi Stitched Lehenga",
        image:l9,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Embroidered Semi Stitched Lehenga",
        image:l10,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Embroidered Semi Stitched Lehenga",
        image:l11,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Embroidered Semi Stitched Lehenga",
        image:l12,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Embroidered Semi Stitched Lehenga",
        image:l13,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Embroidered Semi Stitched Lehenga",
        image:l14,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Embroidered Semi Stitched Lehenga",
        image:l15,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Embroidered Semi Stitched Lehenga",
        image:l16,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Embroidered Semi Stitched Lehenga",
        image:l17,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Embroidered Semi Stitched Lehenga",
        image:l18,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Embroidered Semi Stitched Lehenga",
        image:l19,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Embroidered Semi Stitched Lehenga",
        image:l20,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Embroidered Semi Stitched Lehenga",
        image:l21,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Embroidered Semi Stitched Lehenga",
        image:l22,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Embroidered Semi Stitched Lehenga",
        image:l23,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Embroidered Semi Stitched Lehenga",
        image:l24,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Embroidered Semi Stitched Lehenga",
        image:l25,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allLahenga}
// Gown
let gown=[
     {
        id:1,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {gown}

let allGown=[
    {
        id:1,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g6,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g7,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g8,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g9,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g11,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g12,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g13,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g14,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g15,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g16,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g17,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g18,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g19,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g20,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g21,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g22,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g23,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g24,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g25,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g26,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g27,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g28,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g29,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allGown}

// One-piece
let one_piece=[
    {
        id:1,
        name:"Women One Piece dress",
        image:op1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women One Piece dress",
        image:op2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women One Piece dress",
        image:op3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women One Piece dress",
        image:op4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women One Piece dress",
        image:op5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {one_piece}

let allOne_piece=[
    {
        id:1,
        name:"Women One Piece dress",
        image:op1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women One Piece dress",
        image:op2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women One Piece dress",
        image:op3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women One Piece dress",
        image:op4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women One Piece dress",
        image:op5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women One Piece dress",
        image:op6,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women One Piece dress",
        image:op7,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women One Piece dress",
        image:op8,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women One Piece dress",
        image:op9,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women One Piece dress",
        image:op10,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women One Piece dress",
        image:op11,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women One Piece dress",
        image:op12,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women One Piece dress",
        image:op13,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women One Piece dress",
        image:op14,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women One Piece dress",
        image:op15,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women One Piece dress",
        image:op16,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women One Piece dress",
        image:op17,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women One Piece dress",
        image:op18,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women One Piece dress",
        image:op19,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women One Piece dress",
        image:op20,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women One Piece dress",
        image:op21,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women One Piece dress",
        image:op22,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women One Piece dress",
        image:op23,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Women One Piece dress",
        image:op24,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Women One Piece dress",
        image:op25,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        name:"Women One Piece dress",
        image:op26,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        name:"Women One Piece dress",
        image:op27,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        name:"Women One Piece dress",
        image:op28,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        name:"Women One Piece dress",
        image:op29,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:30,
        name:"Women One Piece dress",
        image:op30,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:31,
        name:"Women One Piece dress",
        image:op31,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:32,
        name:"Women One Piece dress",
        image:op32,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:33,
        name:"Women One Piece dress",
        image:op33,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:34,
        name:"Women One Piece dress",
        image:op34,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allOne_piece}

// Suit-Salwar
let suit_salwar=[
     {
        id:1,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {suit_salwar}

let allSalwar_Suit=[
    {
        id:1,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss6,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss7,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss8,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss9,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss10,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss11,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss12,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss13,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss14,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss15,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss16,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss17,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss18,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss19,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss20,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss21,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss22,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss23,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Women Viscose Rayon Kurta Pant Dupatta",
        image:ss24,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allSalwar_Suit}
// Suit
let suit=[
       {
        id:1,
        name:"Women Coat Solid Suit",
        image:s1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Coat Solid Suit",
        image:s2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Coat Solid Suit",
        image:s3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Coat Solid Suit",
        image:s4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Coat Solid Suit",
        image:s5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {suit}

let allSuit=[
    {
        id:1,
        name:"Women Coat Solid Suit",
        image:s1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Coat Solid Suit",
        image:s2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Coat Solid Suit",
        image:s3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Coat Solid Suit",
        image:s4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Coat Solid Suit",
        image:s5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women Coat Solid Suit",
        image:s6,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women Coat Solid Suit",
        image:s7,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women Coat Solid Suit",
        image:s8,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women Coat Solid Suit",
        image:s9,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women Coat Solid Suit",
        image:s10,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women Coat Solid Suit",
        image:s11,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women Coat Solid Suit",
        image:s12,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women Coat Solid Suit",
        image:s13,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women Coat Solid Suit",
        image:s14,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women Coat Solid Suit",
        image:s15,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women Coat Solid Suit",
        image:s16,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women Coat Solid Suit",
        image:s17,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women Coat Solid Suit",
        image:s18,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women Coat Solid Suit",
        image:s19,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women Coat Solid Suit",
        image:s20,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women Coat Solid Suit",
        image:s21,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women Coat Solid Suit",
        image:s22,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women Coat Solid Suit",
        image:s23,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allSuit}

let tshirt=[
       {
        id:1,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts2,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts3,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts4,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts5,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
]
export {tshirt}

let allT_Shirt=[
    {
        id:1,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts2,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts3,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts4,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts5,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts6,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts7,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts8,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts9,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts10,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts11,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts12,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts13,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts14,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts15,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts16,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts17,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts18,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts19,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts20,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts21,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts22,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts23,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts24,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts25,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export {allT_Shirt}