import g1 from '../../Assets/women/Gown/1.jpeg'
import g2 from '../../Assets/women/Gown/2.jpeg'
import g3 from '../../Assets/women/Gown/3.jpeg'
import g4 from '../../Assets/women/Gown/4.jpeg'
import g5 from '../../Assets/women/Gown/5.jpeg'
import g6 from '../../Assets/women/Gown/6.jpeg'
import g7 from '../../Assets/women/Gown/7.jpeg'
import g8 from '../../Assets/women/Gown/8.jpeg'
import g9 from '../../Assets/women/Gown/9.jpeg'
// import g10 from '../../Assets/women/Gown/10.jpeg'
import g11 from '../../Assets/women/Gown/11.jpeg'
import g12 from '../../Assets/women/Gown/12.jpeg'
import g13 from '../../Assets/women/Gown/13.jpeg'
import g14 from '../../Assets/women/Gown/14.jpeg'
import g15 from '../../Assets/women/Gown/15.jpeg'
import g16 from '../../Assets/women/Gown/16.jpeg'
import g17 from '../../Assets/women/Gown/17.jpeg'
import g18 from '../../Assets/women/Gown/18.jpeg'
import g19 from '../../Assets/women/Gown/19.jpeg'
import g20 from '../../Assets/women/Gown/20.jpeg'
import g21 from '../../Assets/women/Gown/21.jpeg'
import g22 from '../../Assets/women/Gown/22.jpeg'
import g23 from '../../Assets/women/Gown/23.jpeg'
import g24 from '../../Assets/women/Gown/24.jpeg'
import g25 from '../../Assets/women/Gown/25.jpeg'
import g26 from '../../Assets/women/Gown/26.jpeg'
import g27 from '../../Assets/women/Gown/27.jpeg'
import g28 from '../../Assets/women/Gown/28.jpeg'
import g29 from '../../Assets/women/Gown/29.jpeg'

let gown_product=[
    {
        id:1,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g1,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g2,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g3,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g4,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g5,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g6,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g7,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g8,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g9,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    // {
    //     id:10,
    //     name:"Printed Viscose Rayon Stitched Gown",
    //     image:g10,
    //     new_price:"₹1599",
    //     old_price:"₹1999",
    //     offer:"20% off",
    //     rating:"4.3★",
    //     review:1256, 
    //     size:"M , L , XL",
    // },
    {
        id:11,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g11,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g12,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g13,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g14,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g15,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g16,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g17,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g18,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g19,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g20,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g21,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g22,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g23,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g24,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g25,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:26,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g26,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:27,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g27,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:28,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g28,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:29,
        name:"Printed Viscose Rayon Stitched Gown",
        image:g29,
        new_price:"₹1599",
        old_price:"₹1999",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export default gown_product;