import l1 from '../../Assets/women/Lehenga/1.jpeg'
import l2 from '../../Assets/women/Lehenga/2.jpeg'
import l3 from '../../Assets/women/Lehenga/3.jpeg'
import l4 from '../../Assets/women/Lehenga/4.jpeg'
import l5 from '../../Assets/women/Lehenga/5.jpeg'
import l6 from '../../Assets/women/Lehenga/6.jpeg'
import l7 from '../../Assets/women/Lehenga/7.jpeg'
import l8 from '../../Assets/women/Lehenga/8.jpeg'
import l9 from '../../Assets/women/Lehenga/9.jpeg'
import l10 from '../../Assets/women/Lehenga/10.jpeg'
import l11 from '../../Assets/women/Lehenga/11.jpeg'
import l12 from '../../Assets/women/Lehenga/12.jpeg'
import l13 from '../../Assets/women/Lehenga/13.jpeg'
import l14 from '../../Assets/women/Lehenga/14.jpeg'
import l15 from '../../Assets/women/Lehenga/15.jpeg'
import l16 from '../../Assets/women/Lehenga/16.jpeg'
import l17 from '../../Assets/women/Lehenga/17.jpeg'
import l18 from '../../Assets/women/Lehenga/18.jpeg'
import l19 from '../../Assets/women/Lehenga/19.jpeg'
import l20 from '../../Assets/women/Lehenga/20.jpeg'
import l21 from '../../Assets/women/Lehenga/21.jpeg'
import l22 from '../../Assets/women/Lehenga/22.jpeg'
import l23 from '../../Assets/women/Lehenga/23.jpeg'
import l24 from '../../Assets/women/Lehenga/24.jpeg'
import l25 from '../../Assets/women/Lehenga/25.jpeg'

let lehenga_product=[
    {
        id:1,
        name:"Embroidered Semi Stitched Lehenga",
        image:l1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Embroidered Semi Stitched Lehenga",
        image:l2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Embroidered Semi Stitched Lehenga",
        image:l3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Embroidered Semi Stitched Lehenga",
        image:l4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Embroidered Semi Stitched Lehenga",
        image:l5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Embroidered Semi Stitched Lehenga",
        image:l6,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Embroidered Semi Stitched Lehenga",
        image:l7,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Embroidered Semi Stitched Lehenga",
        image:l8,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Embroidered Semi Stitched Lehenga",
        image:l9,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Embroidered Semi Stitched Lehenga",
        image:l10,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Embroidered Semi Stitched Lehenga",
        image:l11,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Embroidered Semi Stitched Lehenga",
        image:l12,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Embroidered Semi Stitched Lehenga",
        image:l13,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Embroidered Semi Stitched Lehenga",
        image:l14,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Embroidered Semi Stitched Lehenga",
        image:l15,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Embroidered Semi Stitched Lehenga",
        image:l16,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Embroidered Semi Stitched Lehenga",
        image:l17,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Embroidered Semi Stitched Lehenga",
        image:l18,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Embroidered Semi Stitched Lehenga",
        image:l19,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Embroidered Semi Stitched Lehenga",
        image:l20,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Embroidered Semi Stitched Lehenga",
        image:l21,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Embroidered Semi Stitched Lehenga",
        image:l22,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Embroidered Semi Stitched Lehenga",
        image:l23,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Embroidered Semi Stitched Lehenga",
        image:l24,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Embroidered Semi Stitched Lehenga",
        image:l25,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export default lehenga_product;