import s1 from '../../Assets/women/Suit/1.jpeg'
import s2 from '../../Assets/women/Suit/2.jpeg'
import s3 from '../../Assets/women/Suit/3.jpeg'
import s4 from '../../Assets/women/Suit/4.jpeg'
import s5 from '../../Assets/women/Suit/5.jpeg'
import s6 from '../../Assets/women/Suit/6.jpeg'
import s7 from '../../Assets/women/Suit/7.jpeg'
import s8 from '../../Assets/women/Suit/8.jpeg'
import s9 from '../../Assets/women/Suit/9.jpeg'
import s10 from '../../Assets/women/Suit/10.jpeg'
import s11 from '../../Assets/women/Suit/11.jpeg'
import s12 from '../../Assets/women/Suit/12.jpeg'
import s13 from '../../Assets/women/Suit/13.jpeg'
import s14 from '../../Assets/women/Suit/14.jpeg'
import s15 from '../../Assets/women/Suit/15.jpeg'
import s16 from '../../Assets/women/Suit/16.jpeg'
import s17 from '../../Assets/women/Suit/17.jpeg'
import s18 from '../../Assets/women/Suit/18.jpeg'
import s19 from '../../Assets/women/Suit/19.jpeg'
import s20 from '../../Assets/women/Suit/20.jpeg'
import s21 from '../../Assets/women/Suit/21.jpeg'
import s22 from '../../Assets/women/Suit/22.jpeg'
import s23 from '../../Assets/women/Suit/23.jpeg'

let suit_product=[
    {
        id:1,
        name:"Women Coat Solid Suit",
        image:s1,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Coat Solid Suit",
        image:s2,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Coat Solid Suit",
        image:s3,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Coat Solid Suit",
        image:s4,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Coat Solid Suit",
        image:s5,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women Coat Solid Suit",
        image:s6,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women Coat Solid Suit",
        image:s7,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women Coat Solid Suit",
        image:s8,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women Coat Solid Suit",
        image:s9,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women Coat Solid Suit",
        image:s10,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women Coat Solid Suit",
        image:s11,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women Coat Solid Suit",
        image:s12,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women Coat Solid Suit",
        image:s13,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women Coat Solid Suit",
        image:s14,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women Coat Solid Suit",
        image:s15,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women Coat Solid Suit",
        image:s16,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women Coat Solid Suit",
        image:s17,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women Coat Solid Suit",
        image:s18,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women Coat Solid Suit",
        image:s19,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women Coat Solid Suit",
        image:s20,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women Coat Solid Suit",
        image:s21,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women Coat Solid Suit",
        image:s22,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women Coat Solid Suit",
        image:s23,
        new_price:"₹15,920",
        old_price:"₹19,899",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export default suit_product;