import ts1 from '../../Assets/women/T-Shirt/1.jpeg'
import ts2 from '../../Assets/women/T-Shirt/2.jpeg'
import ts3 from '../../Assets/women/T-Shirt/3.jpeg'
import ts4 from '../../Assets/women/T-Shirt/4.jpeg'
import ts5 from '../../Assets/women/T-Shirt/5.jpeg'
import ts6 from '../../Assets/women/T-Shirt/6.jpeg'
import ts7 from '../../Assets/women/T-Shirt/7.jpeg'
import ts8 from '../../Assets/women/T-Shirt/8.jpeg'
import ts9 from '../../Assets/women/T-Shirt/9.jpeg'
import ts10 from '../../Assets/women/T-Shirt/10.jpeg'
import ts11 from '../../Assets/women/T-Shirt/11.jpeg'
import ts12 from '../../Assets/women/T-Shirt/12.jpeg'
import ts13 from '../../Assets/women/T-Shirt/13.jpeg'
import ts14 from '../../Assets/women/T-Shirt/14.jpeg'
import ts15 from '../../Assets/women/T-Shirt/15.jpeg'
import ts16 from '../../Assets/women/T-Shirt/16.jpeg'
import ts17 from '../../Assets/women/T-Shirt/17.jpeg'
import ts18 from '../../Assets/women/T-Shirt/18.jpeg'
import ts19 from '../../Assets/women/T-Shirt/19.jpeg'
import ts20 from '../../Assets/women/T-Shirt/20.jpeg'
import ts21 from '../../Assets/women/T-Shirt/21.jpeg'
import ts22 from '../../Assets/women/T-Shirt/22.jpeg'
import ts23 from '../../Assets/women/T-Shirt/23.jpeg'
import ts24 from '../../Assets/women/T-Shirt/24.jpeg'
import ts25 from '../../Assets/women/T-Shirt/25.jpeg'

let tshirt_Women=[
    {
        id:1,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts1,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:2,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts2,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:3,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts3,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:4,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts4,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:5,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts5,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:6,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts6,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:7,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts7,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL", 
    },
    {
        id:8,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts8,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:9,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts9,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:10,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts10,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:11,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts11,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:12,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts12,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:13,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts13,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:14,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts14,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:15,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts15,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256,
        size:"M , L , XL",
    },
    {
        id:16,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts16,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:17,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts17,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:18,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts18,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:19,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts19,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:20,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts20,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:21,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts21,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:22,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts22,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:23,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts23,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:24,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts24,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },
    {
        id:25,
        name:"Women Solid Cotton Blend T-Shirt",
        image:ts25,
        new_price:"₹799",
        old_price:"₹1099",
        offer:"20% off",
        rating:"4.3★",
        review:1256, 
        size:"M , L , XL",
    },

]
export default tshirt_Women;